## logstic

### y = {-1, 1}

In [1]:
from __future__ import division, print_function

import numpy as np


#######################################################################
# Replace TODO with your code
#######################################################################

def tobinary(y):
    return (2*y - 1).astype(int)

def backtozerone(y):
    return ((y+1)/2).astype(int)

def binary_train(X, y, w0=None, b0=None, step_size=0.5, max_iterations=1000):
    """
    Inputs:
    - X: training features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - y: binary training labels, a N dimensional numpy array where 
    N is the number of training points, indicating the labels of 
    training data
    - step_size: step size (learning rate)
    - max_iterations: number of iterations to perform gradient descent

    Returns:
    - w: D-dimensional vector, a numpy array which is the weight 
    vector of logistic regression
    - b: scalar, which is the bias of logistic regression

    Find the optimal parameters w and b for inputs X and y.
    Use the *average* of the gradients for all training examples
    multiplied by the step_size to update parameters.
    """
    N, D = X.shape
    assert len(np.unique(y)) == 2


    w = np.zeros(D)
    if w0 is not None:
        w = w0
    
    b = 0
    if b0 is not None:
        b = b0


    """
    TODO: add your code here
    """
    y = tobinary(y)
    ## w = w + step * sum(σ(-yn(wtx + b)) ynxn)/N
    ## b = b + step * sum(σ(-yn(wtx + b)) yn)/N
    ## wtx + b = np.sum(X_train * w.T,1) +b
    # x * np.tile(dfn, (D,1)).T
    for i in range(max_iterations):
        z = y * (np.sum(X * w.T,1) +b)
        sgm = sigmoid(-z) * y
        b1 = b + step_size * np.sum(sgm,0)/N
        w1 = w + step_size * np.sum(X * np.tile(sgm, (D,1)).T, 0)/N
        
        b = b1
        w = w1

    assert w.shape == (D,)
    return w, b


def binary_predict(X, w, b):
    """
    Inputs:
    - X: testing features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    
    Returns:
    - preds: N dimensional vector of binary predictions: {0, 1}
    """
    N, D = X.shape
    preds = np.zeros(N) 


    """
    TODO: add your code here
    """
    y = np.sign(np.sum(X * w, 1) + b)
    preds = backtozerone(y)
    
    assert preds.shape == (N,) 
    return preds


def multinomial_train(X, y, C, 
                     w0=None, 
                     b0=None, 
                     step_size=0.5, 
                     max_iterations=1000):
    """
    Inputs:
    - X: training features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - y: multiclass training labels, a N dimensional numpy array where
    N is the number of training points, indicating the labels of 
    training data
    - C: number of classes in the data
    - step_size: step size (learning rate)
    - max_iterations: number of iterations to perform gradient descent

    Returns:
    - w: C-by-D weight matrix of multinomial logistic regression, where 
    C is the number of classes and D is the dimensionality of features.
    - b: bias vector of length C, where C is the number of classes

    Implement multinomial logistic regression for multiclass 
    classification. Again use the *average* of the gradients for all training 
    examples multiplied by the step_size to update parameters.
    
    You may find it useful to use a special (one-hot) representation of the labels, 
    where each label y_i is represented as a row of zeros with a single 1 in
    the column, that corresponds to the class y_i.
    """

    N, D = X.shape

    w = np.zeros((C, D))
    if w0 is not None:
        w = w0
    
    b = np.zeros(C)
    if b0 is not None:
        b = b0


    """
    TODO: add your code here
    """

    assert w.shape == (C, D)
    assert b.shape == (C,)
    return w, b


def multinomial_predict(X, w, b):
    """
    Inputs:
    - X: testing features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - w: weights of the trained multinomial classifier
    - b: bias terms of the trained multinomial classifier
    
    Returns:
    - preds: N dimensional vector of multiclass predictions.
    Outputted predictions should be from {0, C - 1}, where
    C is the number of classes

    Make predictions for multinomial classifier.
    """
    N, D = X.shape
    C = w.shape[0]
    preds = np.zeros(N) 

    """
    TODO: add your code here
    """   

    assert preds.shape == (N,)
    return preds


def OVR_train(X, y, C, w0=None, b0=None, step_size=0.5, max_iterations=1000):
    """
    Inputs:
    - X: training features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - y: multiclass training labels, a N dimensional numpy array, 
    indicating the labels of each training point
    - C: number of classes in the data
    - w0: initial value of weight matrix
    - b0: initial value of bias term
    - step_size: step size (learning rate)
    - max_iterations: number of iterations to perform gradient descent

    Returns:
    - w: a C-by-D weight matrix of OVR logistic regression
    - b: bias vector of length C

    Implement multiclass classification using one-versus-rest with binary logistic 
    regression as the black-box. Recall that the one-versus-rest classifier is 
    trained by training C different classifiers. 
    """
    N, D = X.shape
    
    w = np.zeros((C, D))
    if w0 is not None:
        w = w0
    
    b = np.zeros(C)
    if b0 is not None:
        b = b0

    """
    TODO: add your code here
    """
    assert w.shape == (C, D), 'wrong shape of weights matrix'
    assert b.shape == (C,), 'wrong shape of bias terms vector'
    return w, b


def OVR_predict(X, w, b):
    """
    Inputs:
    - X: testing features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - w: weights of the trained OVR model
    - b: bias terms of the trained OVR model
    
    Returns:
    - preds: vector of class label predictions.
    Outputted predictions should be from {0, C - 1}, where
    C is the number of classes.

    Make predictions using OVR strategy and probability predictions from binary
    classifiers. 
    """
    N, D = X.shape
    C = w.shape[0]
    preds = np.zeros(N) 
    
    """
    TODO: add your code here
    """

    assert preds.shape == (N,)
    return preds


#######################################################################
# DO NOT MODIFY THE CODE BELOW 
#######################################################################

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def accuracy_score(true, preds):
    return np.sum(true == preds).astype(float) / len(true)

def run_binary():
    from data_loader import toy_data_binary, \
                            data_loader_mnist 

    print('Performing binary classification on synthetic data')
    X_train, X_test, y_train, y_test = toy_data_binary()
        
    w, b = binary_train(X_train, y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
    print('Performing binary classification on binarized MNIST')
    X_train, X_test, y_train, y_test = data_loader_mnist()

    binarized_y_train = [0 if yi < 5 else 1 for yi in y_train] 
    binarized_y_test = [0 if yi < 5 else 1 for yi in y_test] 
    
    w, b = binary_train(X_train, binarized_y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(binarized_y_train, train_preds),
             accuracy_score(binarized_y_test, preds)))

def run_multiclass():
    from data_loader import toy_data_multiclass_3_classes_non_separable, \
                            toy_data_multiclass_5_classes, \
                            data_loader_mnist 
    
    datasets = [(toy_data_multiclass_3_classes_non_separable(), 
                        'Synthetic data', 3), 
                (toy_data_multiclass_5_classes(), 'Synthetic data', 5), 
                (data_loader_mnist(), 'MNIST', 10)]

    for data, name, num_classes in datasets:
        print('%s: %d class classification' % (name, num_classes))
        X_train, X_test, y_train, y_test = data
        
        print('One-versus-rest:')
        w, b = OVR_train(X_train, y_train, C=num_classes)
        train_preds = OVR_predict(X_train, w=w, b=b)
        preds = OVR_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
        print('Multinomial:')
        w, b = multinomial_train(X_train, y_train, C=num_classes)
        train_preds = multinomial_predict(X_train, w=w, b=b)
        preds = multinomial_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))

"""
if __name__ == '__main__':
    
    import argparse
    import sys

    parser = argparse.ArgumentParser()
    parser.add_argument("--type", )
    parser.add_argument("--output")
    args = parser.parse_args()

    if args.output:
            sys.stdout = open(args.output, 'w')

    if not args.type or args.type == 'binary':
        run_binary()

    if not args.type or args.type == 'multiclass':
        run_multiclass()
"""

'\nif __name__ == \'__main__\':\n    \n    import argparse\n    import sys\n\n    parser = argparse.ArgumentParser()\n    parser.add_argument("--type", )\n    parser.add_argument("--output")\n    args = parser.parse_args()\n\n    if args.output:\n            sys.stdout = open(args.output, \'w\')\n\n    if not args.type or args.type == \'binary\':\n        run_binary()\n\n    if not args.type or args.type == \'multiclass\':\n        run_multiclass()\n'

In [2]:
from __future__ import division, print_function
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def accuracy_score(true, preds):
    return np.sum(true == preds).astype(float) / len(true)

def run_binary():
    from data_loader import toy_data_binary, \
                            data_loader_mnist 

    print('Performing binary classification on synthetic data')
    X_train, X_test, y_train, y_test = toy_data_binary()
        
    w, b = binary_train(X_train, y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
    print('Performing binary classification on binarized MNIST')
    X_train, X_test, y_train, y_test = data_loader_mnist()

    binarized_y_train = [0 if yi < 5 else 1 for yi in y_train] 
    binarized_y_test = [0 if yi < 5 else 1 for yi in y_test] 
    
    w, b = binary_train(X_train, binarized_y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(binarized_y_train, train_preds),
             accuracy_score(binarized_y_test, preds)))

def run_multiclass():
    from data_loader import toy_data_multiclass_3_classes_non_separable, \
                            toy_data_multiclass_5_classes, \
                            data_loader_mnist 
    
    datasets = [(toy_data_multiclass_3_classes_non_separable(), 
                        'Synthetic data', 3), 
                (toy_data_multiclass_5_classes(), 'Synthetic data', 5), 
                (data_loader_mnist(), 'MNIST', 10)]

    for data, name, num_classes in datasets:
        print('%s: %d class classification' % (name, num_classes))
        X_train, X_test, y_train, y_test = data
        
        print('One-versus-rest:')
        w, b = OVR_train(X_train, y_train, C=num_classes)
        train_preds = OVR_predict(X_train, w=w, b=b)
        preds = OVR_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
        print('Multinomial:')
        w, b = multinomial_train(X_train, y_train, C=num_classes)
        train_preds = multinomial_predict(X_train, w=w, b=b)
        preds = multinomial_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))

In [3]:
from data_loader import toy_data_binary, \
                            data_loader_mnist 

print('Performing binary classification on synthetic data')
X_train, X_test, y_train, y_test = toy_data_binary()
N, D = X_train.shape

Performing binary classification on synthetic data


/home/lapubu2941/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [4]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [5]:
-1 < 0

True

In [6]:
a= False
1 if a else 0

0

In [7]:
y = -1 <= 0
0 if y else 1

0

In [8]:
def y0ne(a):
    return -1 if a == 0 else 1
y0ne(1)

1

In [9]:
y = np.array([1, 0, 1])
y1 = 2*y - np.ones(len(y)).astype(int)

In [10]:
y1

array([ 1, -1,  1])

In [11]:
(y1 +1)/2

array([1., 0., 1.])

In [12]:
y = np.array([1, 0, 1])
def tobinary(y):
    return (2*y - 1).astype(int)
y1 = tobinary(y)

In [13]:
y1

array([ 1, -1,  1])

In [14]:
type(y_test[1])

numpy.int64

In [15]:
type(y1[0])

numpy.int64

In [16]:
X_train

array([[ 1.09135723, -0.55892185],
       [-0.9425491 , -1.12970685],
       [ 1.0654138 , -0.24751864],
       [ 0.54117719,  1.14927333],
       [ 0.91515201,  1.04416088],
       [-0.94611747, -0.27272357],
       [ 1.05845318, -0.04946371],
       [ 0.88265028,  0.09612078],
       [ 0.75749448,  1.20650897],
       [ 1.054367  ,  0.65020118],
       [-0.48477958, -0.92323325],
       [-0.93222036,  0.05921843],
       [-1.19845466,  2.5733598 ],
       [ 0.80463752, -0.56407863],
       [ 0.88558004, -0.53086877],
       [ 0.88289999, -1.51574411],
       [-0.91447135,  0.01392929],
       [ 0.1243599 , -0.09671311],
       [ 0.78492314,  0.4933179 ],
       [ 1.09711512, -0.06575026],
       [ 1.23054129,  0.24380071],
       [ 1.03449554,  0.38240975],
       [-0.89035836, -0.90431663],
       [ 1.30998108,  2.52693243],
       [-0.80990157,  1.10330188],
       [-1.28907266,  0.05572491],
       [ 1.12140739,  1.42050425],
       [-1.06521415, -0.2403254 ],
       [ 0.89253975,

In [17]:
w = np.array([1, 0])
b = 1
np.sum(X_train * w.T,1) +1

array([ 2.09135723e+00,  5.74508969e-02,  2.06541380e+00,  1.54117719e+00,
        1.91515201e+00,  5.38825266e-02,  2.05845318e+00,  1.88265028e+00,
        1.75749448e+00,  2.05436700e+00,  5.15220425e-01,  6.77796376e-02,
       -1.98454663e-01,  1.80463752e+00,  1.88558004e+00,  1.88289999e+00,
        8.55286536e-02,  1.12435990e+00,  1.78492314e+00,  2.09711512e+00,
        2.23054129e+00,  2.03449554e+00,  1.09641637e-01,  2.30998108e+00,
        1.90098429e-01, -2.89072656e-01,  2.12140739e+00, -6.52141464e-02,
        1.89253975e+00, -3.41060551e-01,  6.25676814e-01,  2.19439988e-01,
        1.84887127e+00,  8.80019126e-02, -4.42084656e-01,  2.12480193e+00,
        2.05053790e+00,  1.50305051e-01,  2.08161545e+00,  2.23107861e+00,
        2.01048861e+00, -2.59590983e-01,  1.67414784e+00,  2.00144856e+00,
       -3.22866695e-01, -5.91006439e-01, -1.38605419e-01,  2.19164958e+00,
        2.39905502e-01,  1.97070587e-02,  1.90094923e+00,  2.30479721e+00,
        2.00955769e+00,  

In [18]:
sigmoid(y1)

array([0.73105858, 0.26894142, 0.73105858])

In [29]:
a = np.array([[1, 2],[3,4], [-1,-2]])

In [30]:
a

array([[ 1,  2],
       [ 3,  4],
       [-1, -2]])

In [34]:
b = np.array([2,1,0])

In [57]:
b1 = np.tile(b, (D,1))

In [58]:
a * b1.T

array([[2, 4],
       [3, 4],
       [0, 0]])

In [59]:
a * np.tile(b,(D,1)).T

array([[2, 4],
       [3, 4],
       [0, 0]])

In [5]:
X=X_train
y=y_train

step_size=0.5
max_iterations=1000

y = tobinary(y)
N, D = X.shape
assert len(np.unique(y)) == 2


w = np.zeros(D)
#w = np.ones(D)

    
b = 0


    ## w = w + step * sum(σ(-yn(wtx + b)) ynxn)
    ## b = b + step * sum(σ(-yn(wtx + b)) yn)
    ## wtx + b = np.sum(X_train * w.T,1) +b
    # x * np.tile(dfn, (D,1)).T
for i in range(max_iterations):
    z = y * (np.sum(X * w.T,1) +b)
    sgm = sigmoid(-z) * y
    b1 = b + step_size * np.sum(sgm,0) 
    w = w + step_size * np.sum(X * np.tile(sgm, (D,1)).T, 0)
    b = b1
    print(b)

2.5
2.5000021392477048
2.500004504155641
2.5000071185186927
2.5000100086380384
2.500013203583367
2.5000167354811595
2.5000206398303564
2.500024955845572
2.5000297268254825
2.5000350005388587
2.5000408296103975
2.5000472718681963
2.5000543905749772
2.5000622543877893
2.5000709367405536
2.500080514052174
2.5000910615978866
2.500102644788394
2.5001153014908235
2.500129006964705
2.500143605219494
2.5001586759085668
2.500173278652628
2.500185468262615
2.5001913954921258
2.5001837070721606
2.5001489428148784
2.5000642169894487
2.4998967529141836
2.4996235364166868
2.4993395982021043
2.4997007230836177
2.503478694786113
2.5199147624987583
2.5702238580700887
2.672352691198324
2.808052770134201
2.9484879892566638
3.080260341253951
3.1987197288274944
3.3021382233694476
3.390012426320893
3.4626358153634578
3.520904082020398
3.5661275858164023
3.599841803554936
3.623643836396759
3.6390728007469724
3.647535969632872
3.6502727086186377
3.6483451365828876
3.642645353318086
3.6339115143250185
3.622747

In [90]:
X=X_train
y=y_train

step_size=0.5
max_iterations=1000

y = tobinary(y)
N, D = X.shape
assert len(np.unique(y)) == 2


w = np.zeros(D)
#w = np.ones(D)

    
b = 0


    ## w = w + step * sum(σ(-yn(wtx + b)) ynxn)
    ## b = b + step * sum(σ(-yn(wtx + b)) yn)
    ## wtx + b = np.sum(X_train * w.T,1) +b
    # x * np.tile(dfn, (D,1)).T
for i in range(max_iterations):
    z = y * (np.sum(X * w.T,1) +b)
    sgm = sigmoid(-z) * y
    b1 = b + step_size * np.sum(sgm,0)
    w = w + step_size * np.sum(X * np.tile(sgm, (D,1)).T, 0)
    b = b1
    print(w)

[86.40673358  9.13932365]
[85.91495494  9.54417921]
[85.42317633  9.94903476]
[84.93139775 10.35389027]
[84.4396192  10.75874576]
[83.94784069 11.16360123]
[83.45606222 11.56845666]
[82.9642838  11.97331205]
[82.47250543 12.3781674 ]
[81.98072712 12.78302271]
[81.48894887 13.18787797]
[80.99717069 13.59273317]
[80.50539259 13.99758832]
[80.01361457 14.40244339]
[79.52183666 14.80729838]
[79.03005885 15.21215328]
[78.53828116 15.61700807]
[78.04650362 16.02186271]
[77.55472626 16.42671715]
[77.06294913 16.83157128]
[76.57117232 17.23642493]
[76.07939597 17.64127775]
[75.58762038 18.04612908]
[75.09584608 18.45097762]
[74.60407412 18.85582084]
[74.11230656 19.26065367]
[73.62054757 19.66546564]
[73.12880593 20.07023435]
[72.63710103 20.47490886]
[72.14547882 20.87936463]
[71.6540571  21.28327124]
[71.16316272 21.68568344]
[70.67376031 22.08374451]
[70.18876531 22.46867986]
[69.71647047 22.81528942]
[69.27475918 23.06900229]
[68.87968948 23.18102455]
[68.52011119 23.18629905]
[68.17593343

[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03717024]
[6.92160694 1.03

In [94]:
w, b = binary_train(X_train, y_train, w0=None, b0=None, step_size=0.5, max_iterations=1000)

In [103]:
y_p =binary_predict(X_test, w, b)

In [98]:
np.sum(X_test * w,1)

array([ -7.19353359,  -2.61333267,  -7.76086775,  -6.32246254,
        -6.26070841,  -5.07407235,  -7.06004274,  -7.62985872,
         5.4318809 ,  -4.01426267,  -7.32428368,   6.61677614,
         6.9437961 ,   5.70044752,  -5.29714975,  -6.10378499,
        -8.41980586,   5.89312265,  -5.43812937,  -5.3487213 ,
         5.92168131,  -5.3690666 ,   6.89601092,  -3.46566879,
        -5.80352395,   8.71534647,   6.69927969,   7.09898784,
        -4.48891231,  -3.51934591,   5.93453687,  -5.0125378 ,
         6.87182428,   5.39028006,  -7.88733429,  -8.21468543,
         5.91538085,   4.6710844 ,  -7.15069737,   5.39049577,
         6.33521218,  -7.92417265,   5.36210775,   7.27134627,
         4.70084971,   8.00748164,  -6.23558912,   6.4245592 ,
         4.84470626,  -5.46249208,   5.14205851,   7.41026591,
        -5.95389882,  -7.89020213,  -9.80730995,   5.93995993,
         7.89876667,  -5.97514936,  -4.12047031,   6.77306607,
        -4.8148656 ,   7.84935386,   7.42510748,   8.02

In [104]:
y_p

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [105]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [106]:
y_p == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,