## logstic

### y = {0,1}

In [1]:
from __future__ import division, print_function

import numpy as np


#######################################################################
# Replace TODO with your code
#######################################################################

def binary_train(X, y, w0=None, b0=None, step_size=0.5, max_iterations=1000):
    """
    Inputs:
    - X: training features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - y: binary training labels, a N dimensional numpy array where 
    N is the number of training points, indicating the labels of 
    training data
    - step_size: step size (learning rate)
    - max_iterations: number of iterations to perform gradient descent

    Returns:
    - w: D-dimensional vector, a numpy array which is the weight 
    vector of logistic regression
    - b: scalar, which is the bias of logistic regression

    Find the optimal parameters w and b for inputs X and y.
    Use the *average* of the gradients for all training examples
    multiplied by the step_size to update parameters.
    """
    N, D = X.shape
    assert len(np.unique(y)) == 2


    w = np.zeros(D)
    if w0 is not None:
        w = w0
    
    b = 0
    if b0 is not None:
        b = b0


    """
    TODO: add your code here
    """
    ## w = w - step * sum(σ(wxn+b)-yn)xn
    ## b = b - step * sum(σ(wxn+b)-yn)
    ## wtx + b = np.sum(X_train * w.T,1) +b
    # x * np.tile(dfn, (D,1)).T
    for i in range(max_iterations):
        z = (np.sum(X * w.T,1) +b)
        sgm = sigmoid(z) - y 
        b = b - step_size * np.sum(sgm,0)
        w = w - step_size * np.sum(X * np.tile(sgm, (D,1)).T, 0)
        
    assert w.shape == (D,)
    return w, b


def binary_predict(X, w, b):
    """
    Inputs:
    - X: testing features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    
    Returns:
    - preds: N dimensional vector of binary predictions: {0, 1}
    """
    N, D = X.shape
    preds = np.zeros(N) 


    """
    TODO: add your code here
    """
    y = np.sum(X * w, 1) + b
    preds = np.round(sigmoid(y))
    
    assert preds.shape == (N,) 
    return preds


def multinomial_train(X, y, C, 
                     w0=None, 
                     b0=None, 
                     step_size=0.5, 
                     max_iterations=1000):
    """
    Inputs:
    - X: training features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - y: multiclass training labels, a N dimensional numpy array where
    N is the number of training points, indicating the labels of 
    training data
    - C: number of classes in the data
    - step_size: step size (learning rate)
    - max_iterations: number of iterations to perform gradient descent

    Returns:
    - w: C-by-D weight matrix of multinomial logistic regression, where 
    C is the number of classes and D is the dimensionality of features.
    - b: bias vector of length C, where C is the number of classes

    Implement multinomial logistic regression for multiclass 
    classification. Again use the *average* of the gradients for all training 
    examples multiplied by the step_size to update parameters.
    
    You may find it useful to use a special (one-hot) representation of the labels, 
    where each label y_i is represented as a row of zeros with a single 1 in
    the column, that corresponds to the class y_i.
    """

    N, D = X.shape

    w = np.zeros((C, D))
    if w0 is not None:
        w = w0
    
    b = np.zeros(C)
    if b0 is not None:
        b = b0


    """
    TODO: add your code here
    """

    assert w.shape == (C, D)
    assert b.shape == (C,)
    return w, b


def multinomial_predict(X, w, b):
    """
    Inputs:
    - X: testing features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - w: weights of the trained multinomial classifier
    - b: bias terms of the trained multinomial classifier
    
    Returns:
    - preds: N dimensional vector of multiclass predictions.
    Outputted predictions should be from {0, C - 1}, where
    C is the number of classes

    Make predictions for multinomial classifier.
    """
    N, D = X.shape
    C = w.shape[0]
    preds = np.zeros(N) 

    """
    TODO: add your code here
    """   

    assert preds.shape == (N,)
    return preds


def OVR_train(X, y, C, w0=None, b0=None, step_size=0.5, max_iterations=1000):
    """
    Inputs:
    - X: training features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - y: multiclass training labels, a N dimensional numpy array, 
    indicating the labels of each training point
    - C: number of classes in the data
    - w0: initial value of weight matrix
    - b0: initial value of bias term
    - step_size: step size (learning rate)
    - max_iterations: number of iterations to perform gradient descent

    Returns:
    - w: a C-by-D weight matrix of OVR logistic regression
    - b: bias vector of length C

    Implement multiclass classification using one-versus-rest with binary logistic 
    regression as the black-box. Recall that the one-versus-rest classifier is 
    trained by training C different classifiers. 
    """
    N, D = X.shape
    
    w = np.zeros((C, D))
    if w0 is not None:
        w = w0
    
    b = np.zeros(C)
    if b0 is not None:
        b = b0

    """
    TODO: add your code here
    """
    
    
    assert w.shape == (C, D), 'wrong shape of weights matrix'
    assert b.shape == (C,), 'wrong shape of bias terms vector'
    return w, b


def OVR_predict(X, w, b):
    """
    Inputs:
    - X: testing features, a N-by-D numpy array, where N is the 
    number of training points and D is the dimensionality of features
    - w: weights of the trained OVR model
    - b: bias terms of the trained OVR model
    
    Returns:
    - preds: vector of class label predictions.
    Outputted predictions should be from {0, C - 1}, where
    C is the number of classes.

    Make predictions using OVR strategy and probability predictions from binary
    classifiers. 
    """
    N, D = X.shape
    C = w.shape[0]
    preds = np.zeros(N) 
    
    """
    TODO: add your code here
    """

    assert preds.shape == (N,)
    return preds


#######################################################################
# DO NOT MODIFY THE CODE BELOW 
#######################################################################

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def accuracy_score(true, preds):
    return np.sum(true == preds).astype(float) / len(true)

def run_binary():
    from data_loader import toy_data_binary, \
                            data_loader_mnist 

    print('Performing binary classification on synthetic data')
    X_train, X_test, y_train, y_test = toy_data_binary()
        
    w, b = binary_train(X_train, y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
    print('Performing binary classification on binarized MNIST')
    X_train, X_test, y_train, y_test = data_loader_mnist()

    binarized_y_train = [0 if yi < 5 else 1 for yi in y_train] 
    binarized_y_test = [0 if yi < 5 else 1 for yi in y_test] 
    
    w, b = binary_train(X_train, binarized_y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(binarized_y_train, train_preds),
             accuracy_score(binarized_y_test, preds)))

def run_multiclass():
    from data_loader import toy_data_multiclass_3_classes_non_separable, \
                            toy_data_multiclass_5_classes, \
                            data_loader_mnist 
    
    datasets = [(toy_data_multiclass_3_classes_non_separable(), 
                        'Synthetic data', 3), 
                (toy_data_multiclass_5_classes(), 'Synthetic data', 5), 
                (data_loader_mnist(), 'MNIST', 10)]

    for data, name, num_classes in datasets:
        print('%s: %d class classification' % (name, num_classes))
        X_train, X_test, y_train, y_test = data
        
        print('One-versus-rest:')
        w, b = OVR_train(X_train, y_train, C=num_classes)
        train_preds = OVR_predict(X_train, w=w, b=b)
        preds = OVR_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
        print('Multinomial:')
        w, b = multinomial_train(X_train, y_train, C=num_classes)
        train_preds = multinomial_predict(X_train, w=w, b=b)
        preds = multinomial_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))

"""
if __name__ == '__main__':
    
    import argparse
    import sys

    parser = argparse.ArgumentParser()
    parser.add_argument("--type", )
    parser.add_argument("--output")
    args = parser.parse_args()

    if args.output:
            sys.stdout = open(args.output, 'w')

    if not args.type or args.type == 'binary':
        run_binary()

    if not args.type or args.type == 'multiclass':
        run_multiclass()
"""

'\nif __name__ == \'__main__\':\n    \n    import argparse\n    import sys\n\n    parser = argparse.ArgumentParser()\n    parser.add_argument("--type", )\n    parser.add_argument("--output")\n    args = parser.parse_args()\n\n    if args.output:\n            sys.stdout = open(args.output, \'w\')\n\n    if not args.type or args.type == \'binary\':\n        run_binary()\n\n    if not args.type or args.type == \'multiclass\':\n        run_multiclass()\n'

In [2]:
from __future__ import division, print_function
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def accuracy_score(true, preds):
    return np.sum(true == preds).astype(float) / len(true)

def run_binary():
    from data_loader import toy_data_binary, \
                            data_loader_mnist 

    print('Performing binary classification on synthetic data')
    X_train, X_test, y_train, y_test = toy_data_binary()
        
    w, b = binary_train(X_train, y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
    print('Performing binary classification on binarized MNIST')
    X_train, X_test, y_train, y_test = data_loader_mnist()

    binarized_y_train = [0 if yi < 5 else 1 for yi in y_train] 
    binarized_y_test = [0 if yi < 5 else 1 for yi in y_test] 
    
    w, b = binary_train(X_train, binarized_y_train)
    
    train_preds = binary_predict(X_train, w, b)
    preds = binary_predict(X_test, w, b)
    print('train acc: %f, test acc: %f' % 
            (accuracy_score(binarized_y_train, train_preds),
             accuracy_score(binarized_y_test, preds)))

def run_multiclass():
    from data_loader import toy_data_multiclass_3_classes_non_separable, \
                            toy_data_multiclass_5_classes, \
                            data_loader_mnist 
    
    datasets = [(toy_data_multiclass_3_classes_non_separable(), 
                        'Synthetic data', 3), 
                (toy_data_multiclass_5_classes(), 'Synthetic data', 5), 
                (data_loader_mnist(), 'MNIST', 10)]

    for data, name, num_classes in datasets:
        print('%s: %d class classification' % (name, num_classes))
        X_train, X_test, y_train, y_test = data
        
        print('One-versus-rest:')
        w, b = OVR_train(X_train, y_train, C=num_classes)
        train_preds = OVR_predict(X_train, w=w, b=b)
        preds = OVR_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))
    
        print('Multinomial:')
        w, b = multinomial_train(X_train, y_train, C=num_classes)
        train_preds = multinomial_predict(X_train, w=w, b=b)
        preds = multinomial_predict(X_test, w=w, b=b)
        print('train acc: %f, test acc: %f' % 
            (accuracy_score(y_train, train_preds),
             accuracy_score(y_test, preds)))

In [2]:
from data_loader import toy_data_binary, \
                            data_loader_mnist 

print('Performing binary classification on synthetic data')
X_train, X_test, y_train, y_test = toy_data_binary()
N, D = X_train.shape

Performing binary classification on synthetic data


/home/lapubu2941/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [4]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [5]:
-1 < 0

True

In [6]:
a= False
1 if a else 0

0

In [7]:
y = -1 <= 0
0 if y else 1

0

In [8]:
def y0ne(a):
    return -1 if a == 0 else 1
y0ne(1)

1

In [9]:
y = np.array([1, 0, 1])
y1 = 2*y - np.ones(len(y)).astype(int)

In [10]:
y1

array([ 1, -1,  1])

In [11]:
(y1 +1)/2

array([1., 0., 1.])

In [12]:
y = np.array([1, 0, 1])
def tobinary(y):
    return (2*y - 1).astype(int)
y1 = tobinary(y)

In [13]:
y1

array([ 1, -1,  1])

In [14]:
type(y_test[1])

numpy.int64

In [15]:
type(y1[0])

numpy.int64

In [16]:
X_train

array([[ 1.09135723, -0.55892185],
       [-0.9425491 , -1.12970685],
       [ 1.0654138 , -0.24751864],
       [ 0.54117719,  1.14927333],
       [ 0.91515201,  1.04416088],
       [-0.94611747, -0.27272357],
       [ 1.05845318, -0.04946371],
       [ 0.88265028,  0.09612078],
       [ 0.75749448,  1.20650897],
       [ 1.054367  ,  0.65020118],
       [-0.48477958, -0.92323325],
       [-0.93222036,  0.05921843],
       [-1.19845466,  2.5733598 ],
       [ 0.80463752, -0.56407863],
       [ 0.88558004, -0.53086877],
       [ 0.88289999, -1.51574411],
       [-0.91447135,  0.01392929],
       [ 0.1243599 , -0.09671311],
       [ 0.78492314,  0.4933179 ],
       [ 1.09711512, -0.06575026],
       [ 1.23054129,  0.24380071],
       [ 1.03449554,  0.38240975],
       [-0.89035836, -0.90431663],
       [ 1.30998108,  2.52693243],
       [-0.80990157,  1.10330188],
       [-1.28907266,  0.05572491],
       [ 1.12140739,  1.42050425],
       [-1.06521415, -0.2403254 ],
       [ 0.89253975,

In [17]:
w = np.array([1, 0])
b = 1
np.sum(X_train * w.T,1) +1

array([ 2.09135723e+00,  5.74508969e-02,  2.06541380e+00,  1.54117719e+00,
        1.91515201e+00,  5.38825266e-02,  2.05845318e+00,  1.88265028e+00,
        1.75749448e+00,  2.05436700e+00,  5.15220425e-01,  6.77796376e-02,
       -1.98454663e-01,  1.80463752e+00,  1.88558004e+00,  1.88289999e+00,
        8.55286536e-02,  1.12435990e+00,  1.78492314e+00,  2.09711512e+00,
        2.23054129e+00,  2.03449554e+00,  1.09641637e-01,  2.30998108e+00,
        1.90098429e-01, -2.89072656e-01,  2.12140739e+00, -6.52141464e-02,
        1.89253975e+00, -3.41060551e-01,  6.25676814e-01,  2.19439988e-01,
        1.84887127e+00,  8.80019126e-02, -4.42084656e-01,  2.12480193e+00,
        2.05053790e+00,  1.50305051e-01,  2.08161545e+00,  2.23107861e+00,
        2.01048861e+00, -2.59590983e-01,  1.67414784e+00,  2.00144856e+00,
       -3.22866695e-01, -5.91006439e-01, -1.38605419e-01,  2.19164958e+00,
        2.39905502e-01,  1.97070587e-02,  1.90094923e+00,  2.30479721e+00,
        2.00955769e+00,  

In [18]:
sigmoid(y1)

array([0.73105858, 0.26894142, 0.73105858])

In [29]:
a = np.array([[1, 2],[3,4], [-1,-2]])

In [30]:
a

array([[ 1,  2],
       [ 3,  4],
       [-1, -2]])

In [34]:
b = np.array([2,1,0])

In [57]:
b1 = np.tile(b, (D,1))

In [58]:
a * b1.T

array([[2, 4],
       [3, 4],
       [0, 0]])

In [59]:
a * np.tile(b,(D,1)).T

array([[2, 4],
       [3, 4],
       [0, 0]])

In [91]:
X=X_train
y=y_train

step_size=0.5
max_iterations=1000

y = tobinary(y)
N, D = X.shape
assert len(np.unique(y)) == 2


w = np.zeros(D)
#w = np.ones(D)

    
b = 0


    ## w = w + step * sum(σ(-yn(wtx + b)) ynxn)
    ## b = b + step * sum(σ(-yn(wtx + b)) yn)
    ## wtx + b = np.sum(X_train * w.T,1) +b
    # x * np.tile(dfn, (D,1)).T
for i in range(max_iterations):
    z = y * (np.sum(X * w.T,1) +b)
    sgm = sigmoid(-z) * y
    b1 = b + step_size * np.sum(sgm,0) /N
    w = w + step_size * np.sum(X * np.tile(sgm, (D,1)).T, 0)/N
    b = b1
    print(w)

[0.24687638 0.02611235]
[0.46171881 0.04667291]
[0.64962702 0.06289892]
[0.81524934 0.07584293]
[0.96249473 0.08632396]
[1.09453005 0.09495027]
[1.21388396 0.10216611]
[1.32257059 0.10829557]
[1.42220054 0.11357673]
[1.5140709  0.11818637]
[1.59923522 0.12225744]
[1.67855705 0.12589121]
[1.75275062 0.12916581]
[1.82241186 0.13214227]
[1.88804216 0.13486885]
[1.95006665 0.13738409]
[2.00884849 0.13971909]
[2.06470001 0.14189922]
[2.11789156 0.14394532]
[2.1686585  0.14587467]
[2.21720694 0.14770171]
[2.26371822 0.14943858]
[2.30835271 0.15109557]
[2.35125286 0.15268144]
[2.39254574 0.15420371]
[2.43234512 0.15566886]
[2.47075326 0.15708249]
[2.5078624 0.1584495]
[2.543756   0.15977414]
[2.57850981 0.16106018]
[2.61219278 0.16231091]
[2.64486783 0.16352927]
[2.67659258 0.16471785]
[2.70741984 0.16587898]
[2.7373982  0.16701472]
[2.76657242 0.16812693]
[2.79498386 0.16921728]
[2.82267075 0.17028729]
[2.84966856 0.17133832]
[2.87601023 0.17237159]
[2.90172641 0.17338825]
[2.92684563 0.1743

[5.78893597 0.51356091]
[5.79010131 0.51391531]
[5.79126461 0.51426945]
[5.79242587 0.51462331]
[5.79358509 0.51497691]
[5.79474227 0.51533025]
[5.79589744 0.51568332]
[5.79705058 0.51603612]
[5.79820172 0.51638866]
[5.79935084 0.51674094]
[5.80049796 0.51709295]
[5.80164309 0.51744469]
[5.80278623 0.51779618]
[5.80392738 0.5181474 ]
[5.80506655 0.51849835]
[5.80620375 0.51884904]
[5.80733898 0.51919947]
[5.80847225 0.51954964]
[5.80960356 0.51989955]
[5.81073292 0.52024919]
[5.81186033 0.52059857]
[5.81298581 0.52094769]
[5.81410934 0.52129654]
[5.81523095 0.52164514]
[5.81635064 0.52199347]
[5.8174684  0.52234155]
[5.81858425 0.52268936]
[5.8196982  0.52303692]
[5.82081023 0.52338421]
[5.82192038 0.52373124]
[5.82302863 0.52407802]
[5.82413499 0.52442453]
[5.82523947 0.52477079]
[5.82634207 0.52511679]
[5.8274428  0.52546252]
[5.82854167 0.525808  ]
[5.82963867 0.52615323]
[5.83073382 0.52649819]
[5.83182711 0.5268429 ]
[5.83291856 0.52718735]
[5.83400817 0.52753154]
[5.83509594 0.52

[6.31901871 0.71644594]
[6.31946062 0.71665259]
[6.31990208 0.7168591 ]
[6.32034309 0.71706546]
[6.32078365 0.71727168]
[6.32122377 0.71747774]
[6.32166344 0.71768366]
[6.32210267 0.71788944]
[6.32254145 0.71809507]
[6.32297978 0.71830055]
[6.32341768 0.71850588]
[6.32385513 0.71871107]
[6.32429213 0.71891611]
[6.3247287  0.71912101]
[6.32516483 0.71932576]
[6.32560051 0.71953036]
[6.32603576 0.71973482]
[6.32647057 0.71993913]
[6.32690494 0.7201433 ]
[6.32733887 0.72034732]
[6.32777237 0.7205512 ]
[6.32820542 0.72075493]
[6.32863805 0.72095852]
[6.32907024 0.72116196]
[6.32950199 0.72136526]
[6.32993331 0.72156841]
[6.3303642  0.72177142]
[6.33079466 0.72197429]
[6.33122469 0.72217701]
[6.33165428 0.72237958]
[6.33208344 0.72258201]
[6.33251218 0.7227843 ]
[6.33294048 0.72298644]
[6.33336836 0.72318844]
[6.33379581 0.7233903 ]
[6.33422283 0.72359201]
[6.33464943 0.72379358]
[6.3350756 0.723995 ]
[6.33550134 0.72419629]
[6.33592666 0.72439743]
[6.33635156 0.72459842]
[6.33677603 0.7247

[6.56696023 0.84141052]
[6.56718336 0.84152999]
[6.56740632 0.84164937]
[6.56762911 0.84176868]
[6.56785173 0.8418879 ]
[6.56807418 0.84200704]
[6.56829647 0.8421261 ]
[6.56851858 0.84224509]
[6.56874053 0.84236399]
[6.5689623  0.84248281]
[6.56918391 0.84260155]
[6.56940535 0.84272021]
[6.56962663 0.84283878]
[6.56984773 0.84295728]
[6.57006867 0.8430757 ]
[6.57028944 0.84319404]
[6.57051005 0.8433123 ]
[6.57073048 0.84343048]
[6.57095075 0.84354858]
[6.57117086 0.8436666 ]
[6.5713908  0.84378454]
[6.57161057 0.8439024 ]
[6.57183017 0.84402018]
[6.57204961 0.84413788]
[6.57226889 0.8442555 ]
[6.57248799 0.84437304]
[6.57270694 0.8444905 ]
[6.57292571 0.84460788]
[6.57314432 0.84472519]
[6.57336277 0.84484241]
[6.57358105 0.84495955]
[6.57379917 0.84507662]
[6.57401713 0.84519361]
[6.57423491 0.84531051]
[6.57445254 0.84542734]
[6.57467    0.84554409]
[6.5748873  0.84566076]
[6.57510443 0.84577736]
[6.5753214  0.84589387]
[6.57553821 0.8460103 ]
[6.57575485 0.84612666]
[6.57597134 0.84

[6.70176426 0.91503119]
[6.70189255 0.91510228]
[6.70202075 0.91517331]
[6.70214887 0.9152443 ]
[6.70227691 0.91531525]
[6.70240486 0.91538615]
[6.70253273 0.91545701]
[6.70266052 0.91552782]
[6.70278822 0.91559858]
[6.70291584 0.91566931]
[6.70304338 0.91573998]
[6.70317083 0.91581062]
[6.7032982 0.9158812]
[6.70342549 0.91595175]
[6.7035527  0.91602224]
[6.70367982 0.9160927 ]
[6.70380686 0.91616311]
[6.70393382 0.91623347]
[6.70406069 0.91630379]
[6.70418749 0.91637406]
[6.7043142 0.9164443]
[6.70444083 0.91651448]
[6.70456737 0.91658462]
[6.70469384 0.91665472]
[6.70482022 0.91672477]
[6.70494652 0.91679478]
[6.70507273 0.91686475]
[6.70519887 0.91693467]
[6.70532492 0.91700454]
[6.7054509  0.91707437]
[6.70557679 0.91714416]
[6.70570259 0.9172139 ]
[6.70582832 0.9172836 ]
[6.70595397 0.91735326]
[6.70607953 0.91742287]
[6.70620501 0.91749244]
[6.70633041 0.91756196]
[6.70645573 0.91763144]
[6.70658097 0.91770087]
[6.70670613 0.91777027]
[6.70683121 0.91783961]
[6.7069562  0.917908

[6.77895385 0.95795271]
[6.77903387 0.95799729]
[6.77911384 0.95804185]
[6.77919377 0.95808637]
[6.77927364 0.95813088]
[6.77935347 0.95817535]
[6.77943325 0.9582198 ]
[6.77951298 0.95826422]
[6.77959266 0.95830862]
[6.7796723  0.95835298]
[6.77975189 0.95839732]
[6.77983143 0.95844164]
[6.77991092 0.95848593]
[6.77999036 0.95853019]
[6.78006976 0.95857443]
[6.78014911 0.95861863]
[6.78022841 0.95866282]
[6.78030767 0.95870697]
[6.78038687 0.9587511 ]
[6.78046603 0.95879521]
[6.78054515 0.95883928]
[6.78062421 0.95888333]
[6.78070323 0.95892736]
[6.7807822  0.95897135]
[6.78086112 0.95901533]
[6.78093999 0.95905927]
[6.78101882 0.95910319]
[6.7810976  0.95914708]
[6.78117634 0.95919095]
[6.78125502 0.95923479]
[6.78133366 0.9592786 ]
[6.78141225 0.95932239]
[6.7814908  0.95936615]
[6.78156929 0.95940988]
[6.78164774 0.95945359]
[6.78172615 0.95949727]
[6.78180451 0.95954093]
[6.78188282 0.95958456]
[6.78196108 0.95962817]
[6.78203929 0.95967174]
[6.78211746 0.9597153 ]
[6.78219559 0.95

[6.82781749 0.98516861]
[6.82786887 0.9851972 ]
[6.82792022 0.98522578]
[6.82797154 0.98525434]
[6.82802283 0.98528289]
[6.82807409 0.98531141]
[6.82812532 0.98533993]
[6.82817652 0.98536842]
[6.8282277 0.9853969]
[6.82827884 0.98542536]
[6.82832996 0.98545381]
[6.82838104 0.98548224]
[6.8284321  0.98551065]
[6.82848312 0.98553905]
[6.82853412 0.98556743]
[6.82858509 0.9855958 ]
[6.82863603 0.98562414]
[6.82868694 0.98565248]
[6.82873782 0.98568079]
[6.82878867 0.98570909]
[6.8288395  0.98573737]
[6.82889029 0.98576564]
[6.82894106 0.98579389]
[6.82899179 0.98582213]
[6.8290425  0.98585034]
[6.82909318 0.98587855]
[6.82914383 0.98590673]
[6.82919445 0.9859349 ]
[6.82924504 0.98596306]
[6.8292956  0.98599119]
[6.82934613 0.98601931]
[6.82939664 0.98604742]
[6.82944711 0.98607551]
[6.82949756 0.98610358]
[6.82954798 0.98613164]
[6.82959837 0.98615968]
[6.82964873 0.9861877 ]
[6.82969906 0.98621571]
[6.82974936 0.9862437 ]
[6.82979964 0.98627168]
[6.82984988 0.98629964]
[6.8299001  0.9863

[6.85895226 1.00247915]
[6.85898609 1.00249793]
[6.85901989 1.00251671]
[6.85905368 1.00253547]
[6.85908745 1.00255422]
[6.8591212  1.00257297]
[6.85915493 1.0025917 ]
[6.85918864 1.00261042]
[6.85922233 1.00262913]
[6.85925601 1.00264783]
[6.85928966 1.00266652]
[6.8593233 1.0026852]
[6.85935692 1.00270387]
[6.85939052 1.00272253]
[6.8594241  1.00274118]
[6.85945766 1.00275982]
[6.85949121 1.00277845]
[6.85952473 1.00279707]
[6.85955824 1.00281567]
[6.85959173 1.00283427]
[6.8596252  1.00285286]
[6.85965865 1.00287143]
[6.85969208 1.00289   ]
[6.85972549 1.00290855]
[6.85975889 1.0029271 ]
[6.85979227 1.00294563]
[6.85982562 1.00296416]
[6.85985896 1.00298267]
[6.85989228 1.00300118]
[6.85992559 1.00301967]
[6.85995887 1.00303815]
[6.85999214 1.00305662]
[6.86002538 1.00307509]
[6.86005861 1.00309354]
[6.86009182 1.00311198]
[6.86012501 1.00313041]
[6.86015819 1.00314883]
[6.86019134 1.00316724]
[6.86022448 1.00318565]
[6.8602576  1.00320404]
[6.8602907  1.00322242]
[6.86032378 1.0032

[6.87723969 1.01262712]
[6.87726344 1.01264028]
[6.87728718 1.01265345]
[6.87731091 1.0126666 ]
[6.87733462 1.01267975]
[6.87735832 1.01269289]
[6.877382   1.01270602]
[6.87740568 1.01271914]
[6.87742934 1.01273226]
[6.87745298 1.01274537]
[6.87747662 1.01275848]
[6.87750024 1.01277157]
[6.87752385 1.01278466]
[6.87754744 1.01279774]
[6.87757102 1.01281082]
[6.87759459 1.01282389]
[6.87761815 1.01283695]
[6.8776417 1.01285  ]
[6.87766523 1.01286305]
[6.87768875 1.01287609]
[6.87771225 1.01288912]
[6.87773574 1.01290214]
[6.87775922 1.01291516]
[6.87778269 1.01292817]
[6.87780614 1.01294118]
[6.87782959 1.01295417]
[6.87785301 1.01296716]
[6.87787643 1.01298014]
[6.87789983 1.01299312]
[6.87792322 1.01300609]
[6.8779466  1.01301905]
[6.87796997 1.013032  ]
[6.87799332 1.01304495]
[6.87801666 1.01305789]
[6.87803998 1.01307082]
[6.8780633  1.01308375]
[6.8780866  1.01309666]
[6.87810989 1.01310957]
[6.87813316 1.01312248]
[6.87815643 1.01313538]
[6.87817968 1.01314827]
[6.87820291 1.0131

[6.89034665 1.0198896 ]
[6.89036328 1.01989881]
[6.89037991 1.01990802]
[6.89039652 1.01991722]
[6.89041313 1.01992642]
[6.89042973 1.01993561]
[6.89044632 1.01994479]
[6.8904629  1.01995398]
[6.89047947 1.01996315]
[6.89049604 1.01997232]
[6.89051259 1.01998149]
[6.89052913 1.01999065]
[6.89054567 1.01999981]
[6.8905622  1.02000896]
[6.89057871 1.0200181 ]
[6.89059522 1.02002724]
[6.89061172 1.02003638]
[6.89062822 1.02004551]
[6.8906447  1.02005464]
[6.89066117 1.02006376]
[6.89067764 1.02007288]
[6.89069409 1.02008199]
[6.89071054 1.0200911 ]
[6.89072698 1.0201002 ]
[6.89074341 1.02010929]
[6.89075983 1.02011839]
[6.89077624 1.02012747]
[6.89079264 1.02013656]
[6.89080903 1.02014563]
[6.89082542 1.02015471]
[6.8908418  1.02016377]
[6.89085816 1.02017284]
[6.89087452 1.02018189]
[6.89089087 1.02019095]
[6.89090721 1.02019999]
[6.89092354 1.02020904]
[6.89093987 1.02021807]
[6.89095618 1.02022711]
[6.89097249 1.02023614]
[6.89098878 1.02024516]
[6.89100507 1.02025418]
[6.89102135 1.02

[6.89921291 1.02479683]
[6.89922478 1.02480339]
[6.89923664 1.02480996]
[6.8992485  1.02481652]
[6.89926035 1.02482307]
[6.89927219 1.02482962]
[6.89928403 1.02483617]
[6.89929586 1.02484272]
[6.89930768 1.02484926]
[6.8993195  1.02485579]
[6.89933131 1.02486233]
[6.89934311 1.02486886]
[6.89935491 1.02487539]
[6.89936671 1.02488191]
[6.89937849 1.02488843]
[6.89939027 1.02489495]
[6.89940205 1.02490146]
[6.89941381 1.02490797]
[6.89942557 1.02491448]
[6.89943733 1.02492098]
[6.89944908 1.02492748]
[6.89946082 1.02493397]
[6.89947256 1.02494047]
[6.89948428 1.02494695]
[6.89949601 1.02495344]
[6.89950772 1.02495992]
[6.89951944 1.0249664 ]
[6.89953114 1.02497287]
[6.89954284 1.02497935]
[6.89955453 1.02498581]
[6.89956622 1.02499228]
[6.8995779  1.02499874]
[6.89958957 1.0250052 ]
[6.89960124 1.02501165]
[6.8996129 1.0250181]
[6.89962455 1.02502455]
[6.8996362  1.02503099]
[6.89964784 1.02503743]
[6.89965948 1.02504387]
[6.89967111 1.0250503 ]
[6.89968273 1.02505673]
[6.89969435 1.0250

[6.90640517 1.02877413]
[6.9064132  1.02877857]
[6.90642123 1.028783  ]
[6.90642925 1.02878744]
[6.90643727 1.02879187]
[6.90644528 1.0287963 ]
[6.90645329 1.02880073]
[6.9064613  1.02880515]
[6.9064693  1.02880957]
[6.9064773  1.02881399]
[6.90648529 1.02881841]
[6.90649328 1.02882283]
[6.90650126 1.02882724]
[6.90650924 1.02883165]
[6.90651721 1.02883606]
[6.90652518 1.02884047]
[6.90653315 1.02884487]
[6.90654111 1.02884927]
[6.90654907 1.02885367]
[6.90655703 1.02885807]
[6.90656498 1.02886246]
[6.90657292 1.02886685]
[6.90658086 1.02887124]
[6.9065888  1.02887563]
[6.90659673 1.02888002]
[6.90660466 1.0288844 ]
[6.90661259 1.02888878]
[6.90662051 1.02889316]
[6.90662842 1.02889753]
[6.90663633 1.02890191]
[6.90664424 1.02890628]
[6.90665215 1.02891065]
[6.90666005 1.02891501]
[6.90666794 1.02891938]
[6.90667583 1.02892374]
[6.90668372 1.0289281 ]
[6.9066916  1.02893246]
[6.90669948 1.02893681]
[6.90670735 1.02894116]
[6.90671522 1.02894551]
[6.90672309 1.02894986]
[6.90673095 1.02

[6.91131482 1.03148734]
[6.91132024 1.03149034]
[6.91132566 1.03149334]
[6.91133108 1.03149633]
[6.9113365  1.03149932]
[6.91134191 1.03150231]
[6.91134732 1.0315053 ]
[6.91135273 1.03150829]
[6.91135814 1.03151128]
[6.91136354 1.03151426]
[6.91136894 1.03151724]
[6.91137433 1.03152023]
[6.91137973 1.03152321]
[6.91138512 1.03152618]
[6.91139051 1.03152916]
[6.91139589 1.03153214]
[6.91140127 1.03153511]
[6.91140665 1.03153808]
[6.91141203 1.03154105]
[6.9114174  1.03154402]
[6.91142277 1.03154699]
[6.91142814 1.03154995]
[6.91143351 1.03155292]
[6.91143887 1.03155588]
[6.91144423 1.03155884]
[6.91144958 1.0315618 ]
[6.91145494 1.03156476]
[6.91146029 1.03156771]
[6.91146564 1.03157067]
[6.91147098 1.03157362]
[6.91147632 1.03157657]
[6.91148166 1.03157952]
[6.911487   1.03158247]
[6.91149233 1.03158542]
[6.91149766 1.03158836]
[6.91150299 1.03159131]
[6.91150832 1.03159425]
[6.91151364 1.03159719]
[6.91151896 1.03160013]
[6.91152428 1.03160306]
[6.91152959 1.031606  ]
[6.9115349  1.03

[6.91468869 1.03335099]
[6.91469234 1.033353  ]
[6.91469597 1.03335501]
[6.91469961 1.03335702]
[6.91470325 1.03335903]
[6.91470688 1.03336103]
[6.91471051 1.03336304]
[6.91471414 1.03336504]
[6.91471777 1.03336705]
[6.91472139 1.03336905]
[6.91472502 1.03337105]
[6.91472864 1.03337305]
[6.91473226 1.03337505]
[6.91473588 1.03337705]
[6.91473949 1.03337905]
[6.91474311 1.03338104]
[6.91474672 1.03338304]
[6.91475033 1.03338503]
[6.91475394 1.03338702]
[6.91475755 1.03338902]
[6.91476115 1.03339101]
[6.91476475 1.033393  ]
[6.91476836 1.03339498]
[6.91477195 1.03339697]
[6.91477555 1.03339896]
[6.91477915 1.03340094]
[6.91478274 1.03340293]
[6.91478633 1.03340491]
[6.91478992 1.03340689]
[6.91479351 1.03340888]
[6.91479709 1.03341086]
[6.91480068 1.03341284]
[6.91480426 1.03341481]
[6.91480784 1.03341679]
[6.91481142 1.03341877]
[6.91481499 1.03342074]
[6.91481857 1.03342272]
[6.91482214 1.03342469]
[6.91482571 1.03342666]
[6.91482928 1.03342863]
[6.91483285 1.0334306 ]
[6.91483641 1.03

In [34]:
X=X_train
y=y_train

step_size=0.5
max_iterations=1000

#y = tobinary(y)
N, D = X.shape
assert len(np.unique(y)) == 2


w = np.zeros(D)
#w = np.ones(D)

    
b = 0


    ## w = w - step * sum(σ(wxn+b)-yn)xn
    ## b = b - step * sum(σ(wxn+b)-yn)
    ## wtx + b = np.sum(X_train * w.T,1) +b
    # x * np.tile(dfn, (D,1)).T
for i in range(max_iterations):
    z = (np.sum(X * w.T,1) +b)
    sgm = sigmoid(z) - y 
    b = b - step_size * np.sum(sgm,0)
    w = w - step_size * np.sum(X * np.tile(sgm, (D,1)).T, 0)
    print(b)

2.5
2.5000021392477048
2.500004504155641
2.5000071185186927
2.5000100086380384
2.500013203583367
2.5000167354811595
2.5000206398303564
2.500024955845572
2.5000297268254825
2.5000350005388587
2.5000408296103975
2.500047271868196
2.500054390574977
2.500062254387789
2.500070936740553
2.5000805140521734
2.500091061597886
2.5001026447883934
2.500115301490823
2.5001290069647046
2.5001436052194936
2.5001586759085663
2.5001732786526274
2.5001854682626146
2.5001913954921253
2.50018370707216
2.500148942814878
2.5000642169894483
2.499896752914183
2.4996235364166863
2.499339598202104
2.4997007230836172
2.5034786947861125
2.5199147624987575
2.570223858070088
2.672352691198323
2.8080527701342
2.948487989256663
3.08026034125395
3.1987197288274936
3.3021382233694467
3.3900124263208924
3.4626358153634564
3.5209040820203965
3.5661275858164014
3.599841803554935
3.6236438363967585
3.639072800746972
3.647535969632872
3.6502727086186373
3.648345136582887
3.642645353318086
3.6339115143250185
3.62274755486907

In [35]:
w, b = binary_train(X_train, y_train, w0=None, b0=None, step_size=0.5, max_iterations=1000)

In [36]:
y_p =binary_predict(X_test, w, b)

In [37]:
np.sum(X_test * w,1)

array([ -8.16336951,  -2.43560776,  -9.00648278,  -7.19670806,
        -7.34618021,  -6.34837233,  -8.35634149,  -9.07129849,
         6.37162733,  -3.94962175,  -8.38959261,   7.27266234,
         8.57298293,   6.33071848,  -6.2881268 ,  -6.78585889,
        -9.90584665,   6.65743033,  -6.56358337,  -5.76214388,
         7.14766421,  -6.33360276,   8.11429372,  -4.04207364,
        -6.73138658,  10.47913348,   7.87770012,   8.62491101,
        -5.25908636,  -3.37177141,   7.13369534,  -5.66236834,
         7.72645908,   6.81120575,  -9.00898401,  -9.21085196,
         7.40017326,   5.34387566,  -8.20556839,   6.25309791,
         7.23351916,  -8.9771956 ,   6.05891788,   8.30907799,
         5.38920126,   9.38889139,  -7.12630952,   7.72269236,
         5.07023082,  -5.92488581,   5.7861725 ,   8.84634521,
        -6.61700086,  -8.7377394 , -11.36714803,   6.76365358,
         9.47589489,  -6.36526793,  -4.12426397,   8.01524905,
        -5.62659769,   9.05046899,   9.03548859,   9.60

In [38]:
y_p

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1.])

In [39]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [40]:
y_p == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [32]:
sgm

array([-0.5,  0.5, -0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5,  0.5,
        0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5, -0.5, -0.5,
        0.5, -0.5,  0.5,  0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5, -0.5,
        0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5,  0.5, -0.5, -0.5,
        0.5,  0.5,  0.5, -0.5,  0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5,
       -0.5,  0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5, -0.5, -0.5, -0.5,
        0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5, -0.5,
       -0.5,  0.5, -0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5,  0.5,
       -0.5,  0.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5,
        0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5,
        0.5,  0.5,  0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5,  0.5, -0.5,
        0.5,  0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5, -0.5,
        0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,
        0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0

In [3]:
x = np.array([[2,1,0],[1,1,1],[3,0,1]])

In [4]:
w = np.array([1,-1,2])

In [8]:
np.dot(x,w)

array([1, 2, 5])