# Tree check

In [1]:
import numpy as np

import data_loader
import decision_tree

###############
# Toy example #
###############
'''
Toy example

dim_1
 ┃
 ╋       ○
 ┃
 ╋   ×       ○
 ┃
 ╋       ×
 ┃
━╋━━━╋━━━╋━━━╋━ dim_0

Print the tree and check the result by yourself!
             
'''
# data
features, labels = data_loader.toy_data_3()

# build the tree
dTree = decision_tree.DecisionTree()
dTree.train(features, labels)

# print
dTree.print_tree()

node 0{
 num of sample / cls: 2 2 


TypeError: unsupported format string passed to NoneType.__format__

## Conditional Entropy

In [2]:
a = [[1,3],[3,4],[3,0]]
print(a)
print(type(a))
print(len(a))
print([len(x) for x in a])

[[1, 3], [3, 4], [3, 0]]
<class 'list'>
3
[2, 2, 2]


In [3]:
print(np.log2(1))
print(np.log2(2))

0.0
1.0


In [4]:
np.sum(a, axis=1)

array([4, 7, 3])

In [5]:
np.sum(a)

14

In [6]:
branches = [[1,3],[3,4],[3,0]]

In [7]:
            branp = np.array(branches)
            B, C = branp.shape
            # B axis = 0, C axis =1. B x C numpy array

            # number of element for each branch B x 1
            bele = np.sum(branp, axis = 1).reshape((B,1))
            
            # each class probability for each branch B x C
            Py_a = np.divide(branp, bele)
            
            # each branch probability
            Pa = bele / np.sum(branp)
            
            # entropy for each branch B x 1
            H = np.sum(- np.multiply(Py_a, (np.ma.log2(Py_a)).filled(0)), axis=1)
            
            # conditional entropy
            coen = np.dot(H,Pa)[0].tolist()

In [8]:
np.divide(branp, bele)

array([[0.25      , 0.75      ],
       [0.42857143, 0.57142857],
       [1.        , 0.        ]])

In [9]:
bele / np.sum(branp)

array([[0.28571429],
       [0.5       ],
       [0.21428571]])

In [10]:
np.multiply(Py_a, np.log2(Py_a))

/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.
/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


array([[-0.5       , -0.31127812],
       [-0.52388247, -0.46134567],
       [ 0.        ,         nan]])

In [11]:
#from numpy import ma

res = np.ma.filled(np.log2(np.ma.masked_equal(Py_a, 0)), 0)
print(res)

[[-2.         -0.4150375 ]
 [-1.22239242 -0.80735492]
 [ 0.          0.        ]]


/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log2
  This is separate from the ipykernel package so we can avoid doing imports until


In [12]:
np.ma.filled(np.log2(np.ma.masked_equal(Py_a, 0)), 0)

/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[-2.        , -0.4150375 ],
       [-1.22239242, -0.80735492],
       [ 0.        ,  0.        ]])

In [13]:
res = np.where(Py_a != 0, np.log2(Py_a), 0)

/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


In [14]:
0*np.log2(0)

/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.
/home/lapubu2941/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """Entry point for launching an IPython kernel.


nan

In [15]:
np.ma.masked_equal(Py_a, 0)

masked_array(
  data=[[0.25, 0.75],
        [0.42857142857142855, 0.5714285714285714],
        [1.0, --]],
  mask=[[False, False],
        [False, False],
        [False,  True]],
  fill_value=0.0)

In [16]:
lgpya = (np.ma.log2(Py_a)).filled(0)


In [17]:
lgpya

array([[-2.        , -0.4150375 ],
       [-1.22239242, -0.80735492],
       [ 0.        ,  0.        ]])

In [18]:
- np.multiply(Py_a, (np.ma.log2(Py_a)).filled(0))

array([[ 0.5       ,  0.31127812],
       [ 0.52388247,  0.46134567],
       [-0.        , -0.        ]])

In [19]:
np.sum((- np.multiply(Py_a, (np.ma.log2(Py_a)).filled(0))), axis=1)

array([0.81127812, 0.98522814, 0.        ])

In [20]:
np.dot(H,Pa)

array([0.72440782])

In [21]:
type(coen)

float

In [22]:
type(1.1)

float

In [43]:
        def conditional_entropy(branches):
            '''
            branches: C x B array, 
                      C is the number of classes,
                      B is the number of branches
                      it stores the number of 
                      corresponding training samples 
                      e.g.
                                  ○ ○ ○ ○
                                  ● ● ● ●
                                ┏━━━━┻━━━━┓
                               ○ ○       ○ ○
                               ● ● ● ●
                               
                      branches = [[2,2], [4,0]]
            '''
            ########################################################
            # TODO: compute the conditional entropy
            ########################################################
            
            branp = np.array(branches)
            B, C = branp.shape
            # B axis = 0, C axis =1. B x C numpy array

            # number of element for each branch B x 1
            bele = np.sum(branp, axis = 1).reshape((B,1))
            
            # each class probability for each branch B x C
            Py_a = np.divide(branp, bele)
            
            # each branch probability B x 1
            Pa = bele / np.sum(branp)
            
            # entropy for each branch 1 x B
            H = np.sum(- np.multiply(Py_a, (np.ma.log2(Py_a)).filled(0)), axis=1)
            
            # conditional entropy
            coen = np.dot(H,Pa)[0].tolist()
            
            return coen

## tree construction

In [23]:
print(features)
print(labels)

[[1, 2], [2, 1], [2, 3], [3, 2]]
[0, 0, 1, 1]


In [26]:
print(features[0])
print(len(features[0]))
print(len(features))

[1, 2]
2
4


In [27]:
np.unique(labels)

array([0, 1])

In [29]:
print(np.unique([0,1,1,0,2,5]))
print(len(np.unique([0,1,1,0,2,5])))

[0 1 2 5]
4


In [36]:
features[0]

[1, 2]

In [49]:
idx_dim = 0
feanp = np.array(features)
labnp = np.array(labels)
Ctemp = len(np.unique(labels))

In [66]:
            # number of discrete value == number of branch
            Btemp = len(set([row[idx_dim] for row in features]))
            branchtm = np.zeros((Ctemp, Btemp))
            for valfea in list(set([row[idx_dim] for row in features])):
                #childbool = valfea >  feanp[:,idx_dim]
                print(valfea)
            #print(~childbool)

            
            labnp[childbool]

1
2
3


array([0, 0, 1])

In [37]:
[row[0] for row in features]

[1, 2, 2, 3]

In [38]:
fea_uni = list(set([row[0] for row in features]))
print(fea_uni)

[1, 2, 3]


In [39]:
for i in list(set([row[0] for row in features])):
    print(i)

1
2
3


In [46]:
feanp[:,idx_dim]

array([1, 2, 2, 3])

In [58]:
type(childbool)

numpy.ndarray

In [60]:
labnp[childbool]

array([0, 0, 1])

In [ ]:
np