# GMM

In [1]:
import numpy as np
from kmeans import KMeans

from data_loader import toy_dataset, load_digits
from utils import Figure
from matplotlib.patches import Ellipse

class GMM():
    '''
        Fits a Gausian Mixture model to the data.

        attrs:
            n_cluster : Number of mixtures (Int)
            e : error tolerance (Float) 
            max_iter : maximum number of updates (Int)
            init : initialization of means and variance
                Can be 'random' or 'kmeans' 
            means : means of Gaussian mixtures (n_cluster X D numpy array)
            variances : variance of Gaussian mixtures (n_cluster X D X D numpy array) 
            pi_k : mixture probabilities of different component ((n_cluster,) size numpy array)
    '''

    def __init__(self, n_cluster, init='k_means', max_iter=100, e=0.0001):
        self.n_cluster = n_cluster
        self.e = e
        self.max_iter = max_iter
        self.init = init
        self.means = None
        self.variances = None
        self.pi_k = None

    def fit(self, x):
        '''
            Fits a GMM to x.

            x: is a NXD size numpy array
            updates:
                self.means
                self.variances
                self.pi_k
        '''
        assert len(x.shape) == 2, 'x can only be 2 dimensional'

        np.random.seed(42)
        N, D = x.shape

        if (self.init == 'k_means'):
            # TODO
            # - comment/remove the exception
            # - initialize means using k-means clustering
            # - compute variance and pi_k (see P4.pdf)

            # DONOT MODIFY CODE ABOVE THIS LINE
            #raise Exception(
            #    'Implement initialization of variances, means, pi_k using k-means')
            
            kmean = KMeans(self.n_cluster, self.max_iter, self.e) # self.n_cluster self.max_iter 
            self.means, ymu, _ = kmean.fit(x) # self.means
            self.pi_k = np.array([np.sum(ymu == k) for k in range(self.n_cluster)]) / N #self.pi_k self.n_cluster
            
            # gamma_ik = {0, 1} at this initialize
            self.variances = np.zeros((n_cluster, D, D)) #self.variances self.n_cluster self.means
            for k in range(self.n_cluster):
                xt = x[ymu == k,:] - self.means[k,:] 
                self.variances[k, :, :] = np.dot(np.transpose(xt),xt) / np.sum(ymu==k) #self.variances 
            
            # DONOT MODIFY CODE BELOW THIS LINE

        elif (self.init == 'random'):
            # TODO
            # - comment/remove the exception
            # - initialize means randomly
            # - initialize variance to be identity and pi_k to be uniform

            # DONOT MODIFY CODE ABOVE THIS LINE
            #raise Exception(
            #    'Implement initialization of variances, means, pi_k randomly')
            
            self.means = np.random.rand(self.n_cluster, D) # self.means self.n_cluster
            self.pi_k = np.random.rand(self.n_cluster,) #self.pi_k self.n_cluster
            self.variances = np.random.rand(self.n_cluster, D, D) #self.variances self.n_cluster
            
            # DONOT MODIFY CODE BELOW THIS LINE

        else:
            raise Exception('Invalid initialization provided')

        # TODO
        # - comment/remove the exception
        # - Use EM to learn the means, variances, and pi_k and assign them to self
        # - Update until convergence or until you have made self.max_iter updates.
        # - Return the number of E/M-Steps executed (Int) 
        # Hint: Try to separate E & M step for clarity
        # DONOT MODIFY CODE ABOVE THIS LINE
        #raise Exception('Implement fit function (filename: gmm.py)')
        
        #4
        l = self.compute_log_likelihood(x, self.means, self.variances, self.pi_k)
        gamma = np.zeros((N, self.n_cluster))
        for itr in range(self.max_iter):
            print("Iteration,", itr)
            # 6 E step
            for n in range(N):
                sumnorm = .0
                normk = np.zeros(self.n_cluster)
                for k in range(self.n_cluster):
                    normk[k]= self.pi_k[k] * self.Gaussian_pdf(
                        self.means[k,:], self.variances[k,:]).getLikelihood(x[n,:])
                    sumnorm += normk[k]
                gamma[n, :] = normk / sumnorm
            
            # 7 M step
            # eq.(5)
            Nk = np.sum(gamma, axis=0)
            
            # eq.(6)
            means2 = np.zeros(self.means.shape)
            for k in range(self.n_cluster):
                means2[k, :] = np.sum(np.multiply(gamma[:, k].reshape(gamma.shape[0],1), x), axis=0)/Nk[k]
            
            
            # eq.(7)
            variances2 = np.zeros(self.variances.shape)
            for k in range(self.n_cluster):
                sumvark = .0
                for n in range(N):
                    xmu = x[n, :] - self.means[k, :]
                    sumvark += gamma[n, k]*(np.dot(np.transpose(xmu), xmu))
                variances2[k, :, :] = sumvark / Nk[k]
            
            # eq.(8)
            self.pi_k = Nk / N
            self.means = means2
            self.variances = variances2
            
            l1 = self.compute_log_likelihood(x, self.means, self.variances, self.pi_k)
            
            # stop condition
            if abs(l-l1) < self.e:
                break
            l = l1
        
        # DONOT MODIFY CODE BELOW THIS LINE


    def sample(self, N):
        '''
        sample from the GMM model

        N is a positive integer
        return : NXD array of samples

        '''
        assert type(N) == int and N > 0, 'N should be a positive integer'
        np.random.seed(42)
        if (self.means is None):
            raise Exception('Train GMM before sampling')

        # TODO
        # - comment/remove the exception
        # - generate samples from the GMM
        # - return the samples

        # DONOT MODIFY CODE ABOVE THIS LINE
        raise Exception('Implement sample function in gmm.py')
        # DONOT MODIFY CODE BELOW THIS LINE
        return samples        

    def compute_log_likelihood(self, x, means=None, variances=None, pi_k=None):
        '''
            Return log-likelihood for the data

            x is a NXD matrix
            return : a float number which is the log-likelihood of data
        '''
        assert len(x.shape) == 2,  'x can only be 2 dimensional'
        if means is None:
            means = self.means
        if variances is None:
            variances = self.variances
        if pi_k is None:
            pi_k = self.pi_k    
        # TODO
        # - comment/remove the exception
        # - calculate log-likelihood using means, variances and pi_k attr in self
        # - return the log-likelihood (Float)
        # Note: you can call this function in fit function (if required)
        # DONOT MODIFY CODE ABOVE THIS LINE
        #raise Exception('Implement compute_log_likelihood function in gmm.py')
        N, D = x.shape
        K = self.pi_k.shape[0]
        log_likelihood = .0
        #for n in range(3):
        for n in range(N):
            lnk = .0
            for k in range(K):
                lnk += self.pi_k[k] * self.Gaussian_pdf(
                    self.means[k,:], self.variances[k,:]).getLikelihood(x[n,:])
            log_likelihood += np.log(lnk)
        
        # DONOT MODIFY CODE BELOW THIS LINE
        return log_likelihood

    class Gaussian_pdf():
        def __init__(self,mean,variance):
            self.mean = mean
            self.variance = variance
            self.c = None
            self.inv = None
            '''
                Input: 
                    Means: A 1 X D numpy array of the Gaussian mean
                    Variance: A D X D numpy array of the Gaussian covariance matrix
                Output: 
                    None: 
            '''
            # TODO
            # - comment/remove the exception
            # - Set self.inv equal to the inverse the variance matrix (after ensuring it is full rank - see P4.pdf)
            # - Set self.c equal to ((2pi)^D) * det(variance) (after ensuring the variance matrix is full rank)
            # Note you can call this class in compute_log_likelihood and fit
            # DONOT MODIFY CODE ABOVE THIS LINE
            #raise Exception('Impliment Guassian_pdf __init__')
            D = self.variance.shape[0] # self.variance
            while np.linalg.matrix_rank(self.variance) != len(self.variance): # self.variance
                self.variance = self.variance + 1e-3 * np.identity(len(self.variance)) # self.variance
            self.inv = np.linalg.inv(self.variance) # self.variance self.inv
            self.c = ((2*np.pi)**D) * np.linalg.det(self.variance) # self.c self.variance            
            
            
            # DONOT MODIFY CODE BELOW THIS LINE

        def getLikelihood(self,x):
            '''
                Input: 
                    x: a 1 X D numpy array representing a sample
                Output: 
                    p: a numpy float, the likelihood sample x was generated by this Gaussian
                Hint: 
                    p = e^(-0.5(x-mean)*(inv(variance))*(x-mean)') / sqrt(c)
                    where ' is transpose and * is matrix multiplication
            '''
            #TODO
            # - Comment/remove the exception
            # - Calculate the likelihood of sample x generated by this Gaussian
            # Note: use the described implementation of a Gaussian to ensure compatibility with the solutions
            # DONOT MODIFY CODE ABOVE THIS LINE
            #raise Exception('Impliment Guassian_pdf getLikelihood')
            p = np.exp(-0.5 * np.dot(np.dot((x - self.mean), self.inv),
                                     np.transpose(x - self.mean))) / np.sqrt(self.c) # self.mean self.inv self.c
            # DONOT MODIFY CODE BELOW THIS LINE
            return p

In [2]:
x, y = toy_dataset(4, 100)
init = ['k_means', 'random']

n_cluster = 4
max_iter=1000
e=1e-6
## gmm = GMM(n_cluster=n_cluster, max_iter=1000, init=, e=1e-6)

# after fit
np.random.seed(42)
N, D = x.shape

## 3.1 self.fit()

### 3: Initialize

In [40]:
            #if (self.init == 'k_means'):
            # TODO
            # - comment/remove the exception
            # - initialize means using k-means clustering
            # - compute variance and pi_k (see P4.pdf)
            kmean = KMeans(n_cluster, max_iter, e) # self.n_cluster self.max_iter 
            means, ymu, _ = kmean.fit(x) # self.means
            
            pi_k = np.array([np.sum(ymu == k) for k in range(n_cluster)]) / N #self.pi_k self.n_cluster
            
            # gamma_ik = {0, 1} at this initialize
            variances = np.zeros((n_cluster, D, D)) #self.variances self.n_cluster
            for k in range(n_cluster):
                xt = x[ymu == k,:] - means[k,:]
                variances[k, :, :] = np.dot(np.transpose(xt),xt) / np.sum(ymu==k) #self.variances 
            

In [6]:
means

array([[ 0.10915641,  4.06440898],
       [-0.07648207, -3.90558464],
       [-4.06823887, -0.10771231],
       [ 3.85187516,  0.07434196]])

In [7]:
pi_k.shape

(4,)

In [5]:
ymu

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,

In [8]:
np.sum(ymu == 0)

98

In [11]:
# self.pi_k
np.array([np.sum(ymu == k) for k in set(ymu)]) /N

array([0.245, 0.25 , 0.25 , 0.255])

In [23]:
np.array([np.sum(ymu == k) for k in range(n_cluster)]) /N

array([0.245, 0.25 , 0.25 , 0.255])

In [22]:
xt = x[ymu == 0,:] - means[0,:]
np.dot(np.transpose(xt),xt) / np.sum(ymu==0)

array([[ 0.89698826, -0.00362015],
       [-0.00362015,  0.88002076]])

In [25]:
variances = np.zeros((n_cluster, D, D))
for k in range(n_cluster):
    xt = x[ymu == k,:] - means[k,:]
    variances[k, :, :] = np.dot(np.transpose(xt),xt) / np.sum(ymu==k)
print(variances)

[[[ 0.89698826 -0.00362015]
  [-0.00362015  0.88002076]]

 [[ 0.99401738 -0.12779475]
  [-0.12779475  1.06004803]]

 [[ 0.94838648  0.07112622]
  [ 0.07112622  1.00335619]]

 [[ 0.76487677 -0.03873293]
  [-0.03873293  1.04969266]]]


In [20]:
aa = np.array([[1,0],[0,1],[1,1]])
np.dot(aa.T, aa)

array([[2, 1],
       [1, 2]])

In [12]:
D

2

In [31]:
        #elif (self.init == 'random'):
            # TODO
            # - comment/remove the exception
            # - initialize means randomly
            # - initialize variance to be identity and pi_k to be uniform
            means = np.random.rand(n_cluster, D) # self.means self.n_cluster
            pi_k = np.random.rand(n_cluster,) #self.pi_k self.n_cluster
            variances = np.random.rand(n_cluster, D, D) #self.variances self.n_cluster

In [25]:
means

array([[9.38552709e-01, 7.78765841e-04],
       [9.92211559e-01, 6.17481510e-01],
       [6.11653160e-01, 7.06630522e-03],
       [2.30624250e-02, 5.24774660e-01]])

In [32]:
pi_k

array([0.17336465, 0.39106061, 0.18223609, 0.75536141])

In [33]:
pi_k.shape

(4,)

In [60]:
kk = pi_k.shape[0]
print(kk)

4


In [29]:
variances

array([[[0.02306243, 0.52477466],
        [0.39986097, 0.04666566]],

       [[0.97375552, 0.23277134],
        [0.09060643, 0.61838601]],

       [[0.38246199, 0.98323089],
        [0.46676289, 0.85994041]],

       [[0.68030754, 0.45049925],
        [0.01326496, 0.94220176]]])

### 4: Compute the log-likelihood l

In [ ]:
        """#def compute_log_likelihood(self, x, means=None, variances=None, pi_k=None):
        '''
            Return log-likelihood for the data

            x is a NXD matrix
            return : a float number which is the log-likelihood of data
        '''
        assert len(x.shape) == 2,  'x can only be 2 dimensional'
        if means is None:
            means = self.means
        if variances is None:
            variances = self.variances
        if pi_k is None:
            pi_k = self.pi_k 
        """
        # TODO
        # - comment/remove the exception
        # - calculate log-likelihood using means, variances and pi_k attr in self
        # - return the log-likelihood (Float)
        # Note: you can call this function in fit function (if required)
        # DONOT MODIFY CODE ABOVE THIS LINE
        #raise Exception('Implement compute_log_likelihood function in gmm.py')
        # DONOT MODIFY CODE BELOW THIS LINE
        
        #return log_likelihood



In [46]:
        """
        class Gaussian_pdf():
        def __init__(self,mean,variance):
            self.mean = mean
            self.variance = variance
            self.c = None
            self.inv = None
            '''
                Input: 
                    Means: A 1 X D numpy array of the Gaussian mean
                    Variance: A D X D numpy array of the Gaussian covariance matrix
                Output: 
                    None: 
            '''
            # TODO
            # - comment/remove the exception
            # - Set self.inv equal to the inverse the variance matrix (after ensuring it is full rank - see P4.pdf)
            # - Set self.c equal to ((2pi)^D) * det(variance) (after ensuring the variance matrix is full rank)
            # Note you can call this class in compute_log_likelihood and fit
            # DONOT MODIFY CODE ABOVE THIS LINE
            raise Exception('Impliment Guassian_pdf __init__')
                
        """
        mean = means[0,:]
        variance = variances[0,:,:]

In [47]:
            D = variance.shape[0]
            while np.linalg.matrix_rank(variance) != len(variance): # self.variance
                variance = variance + 1e-3 * np.identity(len(variance)) # self.variance
            inv = np.linalg.inv(variance) # self.variance self.inv
            c = ((2*np.pi)**D) * np.linalg.det(variance) # self.c self.variance
        
            # DONOT MODIFY CODE BELOW THIS LINE



In [52]:
print(inv)

[[1.1148603  0.00458621]
 [0.00458621 1.1363557 ]]


In [48]:
x = x[0,:]

In [49]:
print(x)

[ 4.49671415 -0.1382643 ]


In [58]:
            #def getLikelihood(self,x):
            '''
                Input: 
                    x: a 1 X D numpy array representing a sample
                Output: 
                    p: a numpy float, the likelihood sample x was generated by this Gaussian
                Hint: 
                    p = e^(-0.5(x-mean)*(inv(variance))*(x-mean)') / sqrt(c)
                    where ' is transpose and * is matrix multiplication
            '''
            #TODO
            # - Comment/remove the exception
            # - Calculate the likelihood of sample x generated by this Gaussian
            # Note: use the described implementation of a Gaussian to ensure compatibility with the solutions
            # DONOT MODIFY CODE ABOVE THIS LINE
            #raise Exception('Impliment Guassian_pdf getLikelihood')
            p = np.exp(-0.5 * np.dot(
                np.dot(
                    (x - mean), inv), np.transpose(
                    x - mean))) / np.sqrt(c)# self.mean self.inv self.c
            print(p)
            # DONOT MODIFY CODE BELOW THIS LINE
            #return p

1.8672945049698254e-10


In [54]:
np.dot(np.array([1,2]),np.array([[1],[1]]))

array([3])

In [ ]:
x, y = toy_dataset(4, 100)

In [36]:
ain = np.array([[0.8, 0.8],[.5,.5]])
print(1e-3 * np.identity(len(ain)))
while np.linalg.matrix_rank(ain) != len(ain):
    ain = ain + 1e-3 * np.identity(len(ain))
ainv = np.linalg.inv(ain)
print(ainv)
print(np.dot(np.array([[0.8, 0.8],[.5,.5]]), ainv))
print(np.dot(ain, ainv))

[[0.001 0.   ]
 [0.    0.001]]
[[ 385.08839354 -614.91160646]
 [-384.31975404  615.68024596]]
[[0.61491161 0.61491161]
 [0.38431975 0.38431975]]
[[ 1.00000000e+00 -5.68434189e-14]
 [ 2.84217094e-14  1.00000000e+00]]


In [30]:
np.linalg.inv(np.array([[0.8, 0.8],[.5,.5]]))

array([[-2.25179981e+16,  3.60287970e+16],
       [ 2.25179981e+16, -3.60287970e+16]])

In [32]:
np.linalg.det(np.array([[0.8, 0.8],[.5,.5]]))

-2.2204460492503083e-17

In [33]:
np.linalg.matrix_rank(np.array([[0.8, 0.8],[.5,.5]]))

1

In [16]:
np.dot(np.array([[1,1],[1,1]]), ainv)

array([[0.49975012, 0.49975012],
       [0.49975012, 0.49975012]])

In [17]:
bb = np.array([[1,1],[2,3]])
bbinv = np.linalg.inv(bb)
np.dot(bb,bbinv)

array([[1., 0.],
       [0., 1.]])

### 5: EM 

In [71]:
gmik = np.random.rand(N,n_cluster).reshape(N,n_cluster)
print(gmik.shape)

(400, 4)


In [72]:
Nk = np.sum(gmik, axis=0)
print(Nk)

[203.26596957 202.98398924 203.7552045  204.03667623]


In [80]:
gmminik = np.array([[1,1,0],[0,1,0],[0,0,1]])
print(gmminik)
print(gmminik[0,:])
nkmi = np.sum(gmminik, axis=0)
np.ravel(gmminik)

[[1 1 0]
 [0 1 0]
 [0 0 1]]
[1 1 0]


array([1, 1, 0, 0, 1, 0, 0, 0, 1])

In [81]:
xmini = np.array([[1,1],[-1,-1],[1,0]])
print(xmini)
print(xmini.shape)

[[ 1  1]
 [-1 -1]
 [ 1  0]]
(3, 2)


In [85]:
#(cluster X N, )
np.tile(np.ravel(gmminik),(xmini.shape[1],1))

array([[1, 1, 0, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 0, 1]])

In [86]:
np.multiply(np.array([[1],[2],[3]]), xmini)

array([[ 1,  1],
       [-2, -2],
       [ 3,  0]])

In [95]:
np.sum(np.multiply(np.array([[1],[2],[3]]), xmini), axis=0)

array([ 2, -1])

In [89]:
np.multiply(np.array([1,2,3]), xmini.T)

array([[ 1, -2,  3],
       [ 1, -2,  0]])

In [93]:
gmminik[:,0].reshape(gmminik.shape[1],1)

array([[1],
       [0],
       [0]])

## test

In [ ]:
import numpy as np
from data_loader import toy_dataset, load_digits
from utils import Figure
from matplotlib.patches import Ellipse


def compute_elipse_params(variance):
    '''
        Compute elipse params for plotting from variance
    '''

    # http://www.cs.cornell.edu/cv/OtherPdf/Ellipse.pdf Slide 17
    # https://stackoverflow.com/a/41821484

    variance_inv = np.linalg.inv(variance)
    a = variance_inv[0, 0]
    c = variance_inv[1, 1]
    b = variance_inv[0, 1] + variance_inv[1, 0]

    M = (variance_inv + variance_inv.T) / 2
    eig, _ = np.linalg.eig(M)
    if (np.abs(eig[0] - a) < np.abs(eig[0] - c)):
        lambda1, lambda2 = eig
    else:
        lambda2, lambda1 = eig

    angle = np.arctan(b / (a - c)) / 2
    return np.sqrt(1 / lambda1), np.sqrt(1 / lambda2), angle


################################################################################
# GMM on 2D toy dataset
# The dataset is generated from N gaussian distributions equally spaced on N radius circle.
# Here, N=4
# You should be able to visualize the learnt gaussian distribution in plots folder
# Complete implementation of fit function for GMM class in gmm.py
################################################################################
x, y = toy_dataset(4, 100)
init = ['k_means', 'random']

for i in init:
    n_cluster = 4
    gmm = GMM(n_cluster=n_cluster, max_iter=1000, init=i, e=1e-6)
    iterations = gmm.fit(x)
    ll = gmm.compute_log_likelihood(x)

    assert gmm.means.shape == (
        n_cluster, 2), 'means should be numpy array with {}X2 shape'.format(n_cluster)

    assert gmm.variances.shape == (
        n_cluster, 2, 2), 'variances should be numpy array with {}X2X2 shape'.format(n_cluster)

    assert gmm.pi_k.shape == (
        n_cluster,), 'pi_k should be numpy vector of size'.format(n_cluster)

    assert iterations > 0 and type(
        iterations) == int, 'Number of updates should be positive integer'

    assert type(ll) == float, 'log-likelihood should be float'

    print('GMM for toy dataset with {} init converged in {} iteration. Final log-likelihood of data: {}'.format(
        i, iterations, ll))

    np.savez('results/gmm_toy_{}.npz'.format(i), iterations=iterations,
             variances=gmm.variances, pi_k=gmm.pi_k, means=gmm.means, log_likelihood=ll, x=x, y=y)

    # plot
    fig = Figure()
    fig.ax.scatter(x[:, 0], x[:, 1], c=y)
    # fig.ax.scatter(gmm.means[:, 0], gmm.means[:, 1], c='red')
    for component in range(n_cluster):
        a, b, angle = compute_elipse_params(gmm.variances[component])
        e = Ellipse(xy=gmm.means[component], width=a * 5, height=b * 5,
                    angle=angle, alpha=gmm.pi_k[component])
        fig.ax.add_artist(e)
    fig.savefig('plots/gmm_toy_dataset_{}.png'.format(i))


################################################################################
# GMM on digits dataset
# We fit a gaussian distribution on digits dataset and show generate samples from the distribution
# Complete implementation of sample function for GMM class in gmm.py
################################################################################

x_train, x_test, y_train, y_test = load_digits()

for i in init:
    n_cluster = 30
    gmm = GMM(n_cluster=n_cluster, max_iter=1000, init=i, e=1e-10)
    iterations = gmm.fit(x_train)
    ll = gmm.compute_log_likelihood(x_train)
    print('GMM for digits dataset with {} init converged in {} iterations. Final log-likelihood of data: {}'.format(i, iterations, ll))

    # plot cluster means
    means = gmm.means
    from matplotlib import pyplot as plt
    l = int(np.ceil(np.sqrt(n_cluster)))

    im = np.zeros((10 * l, 10 * l))
    for m in range(l):
        for n in range(l):
            if (m * l + n < n_cluster):
                im[10 * m:10 * m + 8, 10 * n:10 * n +
                    8] = means[m * l + n].reshape([8, 8])
    im = (im > 0) * im
    plt.imsave('plots/means_{}.png'.format(i), im, cmap='Greys')

    # plot samples
    N = 100
    l = int(np.ceil(np.sqrt(N)))
    samples = gmm.sample(N)

    assert samples.shape == (
        N, x_train.shape[1]), 'Samples should be numpy array with dimensions {}X{}'.format(N, x_train.shape[1])

    im = np.zeros((10 * l, 10 * l))
    for m in range(l):
        for n in range(l):
            if (m * l + n < N):
                im[10 * m: 10 * m + 8, 10 * n: 10 * n +
                    8] = samples[m * l + n].reshape([8, 8])
    im = (im > 0) * im
    plt.imsave('plots/samples_{}.png'.format(i), im, cmap='Greys')

    np.savez('results/gmm_digits_{}.npz'.format(i), iterations=np.array(
        [iterations]), variances=gmm.variances, pi_k=gmm.pi_k, means=gmm.means, samples=samples, log_likelihood=ll, x=x_test, y=y_test)


Iteration, 0


C:\Users\Takato\Anaconda3\lib\site-packages\ipykernel_launcher.py:199: RuntimeWarning: divide by zero encountered in log
C:\Users\Takato\Anaconda3\lib\site-packages\ipykernel_launcher.py:110: RuntimeWarning: invalid value encountered in true_divide


Iteration, 1


C:\Users\Takato\Anaconda3\lib\site-packages\numpy\core\_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
C:\Users\Takato\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:1794: RuntimeWarning: invalid value encountered in greater
  return count_nonzero(S > tol, axis=-1)
