In [1]:
import numpy as np


class KMeans():

    '''
        Class KMeans:
        Attr:
            n_cluster - Number of cluster for kmeans clustering (Int)
            max_iter - maximum updates for kmeans clustering (Int) 
            e - error tolerance (Float)
    '''

    def __init__(self, n_cluster, max_iter=100, e=0.0001):
        self.n_cluster = n_cluster
        self.max_iter = max_iter
        self.e = e

    def fit(self, x):
        '''
            Finds n_cluster in the data x
            params:
                x - N X D numpy array
            returns:
                A tuple
                (centroids a n_cluster X D numpy array,
                y a size (N,) numpy array where cell i is the ith sample's assigned cluster,
                number_of_updates an Int)
            Note: Number of iterations is the number of time you update the assignment
        ''' 
        assert len(x.shape) == 2, "fit function takes 2-D numpy arrays as input"
        np.random.seed(42)
        N, D = x.shape

        # TODO:
        # - comment/remove the exception.
        # - Initialize means by picking self.n_cluster from N data points
        # - Update means and membership until convergence or until you have made self.max_iter updates.
        # - return (means, membership, number_of_updates)

        # DONOT CHANGE CODE ABOVE THIS LINE
        raise Exception(
            'Implement fit function in KMeans class (filename: kmeans.py)')
        # initialize mu and J
        mu0_idx = np.random.choice(range(N), n_cluster)
        mu = x[mu0_idx,:]
        j = 1e15

        def compute_ridx(x, mu):
            A = np.sum(x**2,axis=1).reshape(x.shape[0],1)
            B = np.sum(mu**2,axis=1).reshape(mu.shape[0],1)
            AB = np.dot(x, np.transpose(mu))
            dists = np.sqrt(-2*AB + A + np.transpose(B))
    
            # because r is {0,1}, just return index 
            r = np.argmin(np.transpose(dists), axis=1)
            return np.ravel(r)


        for itr in range(100):
            print(mu[0,:])
    
    
            r_idx = compute_ridx(mu, x)
    
            # r_ik = 0 if xi not in k
            # mu[r_idx,:] means mu_k when r_ik = 1, size N X D
            #j1 = sum(np.sum(np.multiply((x - mu[r_idx,:]), (x - mu[r_idx,:])), axis=1))
            j2 = np.sum(np.multiply((mu[r_idx,:] - x ), (mu[r_idx,:] - x)))
            if abs(j-j2) < e:
                break
            j = j2
            # r_idx
            mu = np.array([np.average(x[r_idx==i,:], axis=0) for i in range(n_cluster)])
        
        # DONOT CHANGE CODE BELOW THIS LINE

class KMeansClassifier():

    '''
        Class KMeansClassifier:
        Attr:
            n_cluster - Number of cluster for kmeans clustering (Int)
            max_iter - maximum updates for kmeans clustering (Int) 
            e - error tolerance (Float) 
    '''

    def __init__(self, n_cluster, max_iter=100, e=1e-6):
        self.n_cluster = n_cluster
        self.max_iter = max_iter
        self.e = e

    def fit(self, x, y):
        '''
            Train the classifier
            params:
                x - N X D size  numpy array
                y - (N,) size numpy array of labels
            returns:
                None
            Stores following attributes:
                self.centroids : centroids obtained by kmeans clustering (n_cluster X D numpy array)
                self.centroid_labels : labels of each centroid obtained by 
                    majority voting ((N,) numpy array) 
        '''

        assert len(x.shape) == 2, "x should be a 2-D numpy array"
        assert len(y.shape) == 1, "y should be a 1-D numpy array"
        assert y.shape[0] == x.shape[0], "y and x should have same rows"

        np.random.seed(42)
        N, D = x.shape
        # TODO:
        # - comment/remove the exception.
        # - Implement the classifier
        # - assign means to centroids
        # - assign labels to centroid_labels

        # DONOT CHANGE CODE ABOVE THIS LINE
        raise Exception(
            'Implement fit function in KMeansClassifier class (filename: kmeans.py)')

        # DONOT CHANGE CODE BELOW THIS LINE

        self.centroid_labels = centroid_labels
        self.centroids = centroids

        assert self.centroid_labels.shape == (self.n_cluster,), 'centroid_labels should be a numpy array of shape ({},)'.format(
            self.n_cluster)

        assert self.centroids.shape == (self.n_cluster, D), 'centroid should be a numpy array of shape {} X {}'.format(
            self.n_cluster, D)

    def predict(self, x):
        '''
            Predict function

            params:
                x - N X D size  numpy array
            returns:
                predicted labels - numpy array of size (N,)
        '''

        assert len(x.shape) == 2, "x should be a 2-D numpy array"

        np.random.seed(42)
        N, D = x.shape
        # TODO:
        # - comment/remove the exception.
        # - Implement the prediction algorithm
        # - return labels

        # DONOT CHANGE CODE ABOVE THIS LINE
        raise Exception(
            'Implement predict function in KMeansClassifier class (filename: kmeans.py)')
        # DONOT CHANGE CODE BELOW THIS LINE
        return labels



In [2]:
import numpy as np
from data_loader import toy_dataset, load_digits
from kmeans import KMeans, KMeansClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from utils import Figure

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
x, y = toy_dataset(4)


In [3]:
#type(x)
N, D = x.shape
print(N,D)

200 2


In [4]:
np.random.seed(42)

n_cluster = 5
max_iter = 100
e = 0.0001

In [179]:
# initialize mu and J
mu0_idx = np.random.choice(range(N), n_cluster)
mu = x[mu0_idx,:]
j = 1e15

def compute_ridx(x, mu):
    A = np.sum(x**2,axis=1).reshape(x.shape[0],1)
    B = np.sum(mu**2,axis=1).reshape(mu.shape[0],1)
    AB = np.dot(x, np.transpose(mu))
    dists = np.sqrt(-2*AB + A + np.transpose(B))
    
    # because r is {0,1}, just return index 
    r = np.argmin(np.transpose(dists), axis=1)
    return np.ravel(r)


for itr in range(100):
    print(mu[0,:])
    
    
    r_idx = compute_ridx(mu, x)
    
    # r_ik = 0 if xi not in k
    # mu[r_idx,:] means mu_k when r_ik = 1, size N X D
    #j1 = sum(np.sum(np.multiply((x - mu[r_idx,:]), (x - mu[r_idx,:])), axis=1))
    j2 = np.sum(np.multiply((mu[r_idx,:] - x ), (mu[r_idx,:] - x)))
    if abs(j-j2) < e:
        break
    j = j2
    # r_idx
    mu = np.array([np.average(x[r_idx==i,:], axis=0) for i in range(n_cluster)])
print(mu[0,:])

[0.52194157 4.29698467]
[-0.09545288  4.14006205]
[-0.16191365  4.13442812]
[-0.16191365  4.13442812]
[-0.16191365  4.13442812]
[-0.16191365  4.13442812]
[-0.16191365  4.13442812]
[-0.16191365  4.13442812]


In [97]:
ma = np.array([[1,1],[2,2]])
xb = np.array([[4,5],[2,2],[0,2],[0,0],[3,3]])
A = np.sum(ma**2,axis=1).reshape(2,1)
B = np.sum(xb**2,axis=1).reshape(5,1)
AB = np.dot(ra,np.transpose(xb))
dists = np.sqrt(-2*AB + A + np.transpose(B))
dists

array([[5.        , 1.41421356, 1.41421356, 1.41421356, 2.82842712],
       [3.60555128, 0.        , 2.        , 2.82842712, 1.41421356]])

In [67]:
r = compute_ridx(ma, xb)
r

array([1, 1, 0, 0, 1], dtype=int64)

In [68]:
for i in list(r):
    print(ma[i,:])

[2 2]
[2 2]
[1 1]
[1 1]
[2 2]


In [180]:
ma[r,:]

array([[2, 2],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2]])

In [69]:
print(ma[r,:])
print(xb - ma[r,:])
np.sum(np.multiply((xb - ma[r,:]), (xb - ma[r,:])), axis=1)

[[2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]]
[[ 2  3]
 [ 0  0]
 [-1  1]
 [-1 -1]
 [ 1  1]]


array([13,  0,  2,  2,  2])

In [70]:
np.sum(np.multiply(xb, xb), axis=1)

array([41,  8,  4,  0, 18])

In [71]:
[i for i in set(list(r))]

[0, 1]

In [75]:
xb[r==1,:]

array([[4, 5],
       [2, 2],
       [3, 3]])

In [77]:
np.average(xb[r==1,:], axis=0)

array([3.        , 3.33333333])

In [78]:
[np.average(xb[r==i,:], axis=0) for i in set(list(r))]

[array([0., 1.]), array([3.        , 3.33333333])]

In [79]:
np.array([np.average(xb[r==i,:], axis=0) for i in set(list(r))])

array([[0.        , 1.        ],
       [3.        , 3.33333333]])

## ~ Test ~

In [3]:
import numpy as np
from data_loader import toy_dataset, load_digits
from kmeans import KMeans, KMeansClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from utils import Figure

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def transform_image(image, code_vectors):
    '''
        Quantize image using the code_vectors

        Return new image from the image by replacing each RGB value in image with nearest code vectors (nearest in euclidean distance sense)

        returns:
            numpy array of shape image.shape
    '''

    assert image.shape[2] == 3 and len(image.shape) == 3, \
        'Image should be a 3-D array with size (?,?,3)'

    assert code_vectors.shape[1] == 3 and len(code_vectors.shape) == 2, \
        'code_vectors should be a 2-D array with size (?,3)'

    # TODO
    # - comment/remove the exception
    # - implement the function

    # DONOT CHANGE CODE ABOVE THIS LINE
    raise Exception(
        'Implement transform_image function (filename:kmeansTest.py)')
    # DONOT CHANGE CODE BELOW THIS LINE
    return new_im

################################################################################
# KMeans on 2D toy dataset
# The dataset is generated from N gaussian distributions equally spaced on N radius circle.
# Here, N=4
# KMeans on this dataset should be able to identify the 4 clusters almost clearly.
################################################################################


def kmeans_toy():
    x, y = toy_dataset(4)
    fig = Figure()
    fig.ax.scatter(x[:, 0], x[:, 1], c=y)
    fig.savefig('plots/toy_dataset_real_labels.png')

    fig.ax.scatter(x[:, 0], x[:, 1])
    fig.savefig('plots/toy_dataset.png')
    n_cluster = 4
    k_means = KMeans(n_cluster=n_cluster, max_iter=100, e=1e-8)
    centroids, membership, i = k_means.fit(x)

    assert centroids.shape == (n_cluster, 2), \
        ('centroids for toy dataset should be numpy array of size {} X 2'
            .format(n_cluster))

    assert membership.shape == (50 * n_cluster,), \
        'membership for toy dataset should be a vector of size 200'

    assert type(i) == int and i > 0,  \
        'Number of updates for toy datasets should be integer and positive'

    print('[success] : kmeans clustering done on toy dataset')
    print('Toy dataset K means clustering converged in {} steps'.format(i))

    fig = Figure()
    fig.ax.scatter(x[:, 0], x[:, 1], c=membership)
    fig.ax.scatter(centroids[:, 0], centroids[:, 1], c='red')
    fig.savefig('plots/toy_dataset_predicted_labels.png')

    np.savez('results/k_means_toy.npz',
             centroids=centroids, step=i, membership=membership, y=y)

################################################################################
# KMeans for image compression
# Here we use k-means for compressing an image
# We load an image 'baboon.tiff',  scale it to [0,1] and compress it.
# The problem can be rephrased as --- "each pixel is a 3-D data point (RGB) and we want to map each point to N points or N clusters.
################################################################################


def kmeans_image_compression():
    im = plt.imread('baboon.tiff')
    N, M = im.shape[:2]
    im = im / 255

    # convert to RGB array
    data = im.reshape(N * M, 3)

    k_means = KMeans(n_cluster=16, max_iter=100, e=1e-6)
    centroids, _, i = k_means.fit(data)

    print('RGB centroids computed in {} iteration'.format(i))
    new_im = transform_image(im, centroids)

    assert new_im.shape == im.shape, \
        'Shape of transformed image should be same as image'

    mse = np.sum((im - new_im)**2) / (N * M)
    print('Mean square error per pixel is {}'.format(mse))
    plt.imsave('plots/compressed_baboon.png', new_im)

    np.savez('results/k_means_compression.npz', im=im, centroids=centroids,
             step=i, new_image=new_im, pixel_error=mse)


################################################################################
# Kmeans for classification
# Here we use k-means for classifying digits
# We find N clusters in the data and label each cluster with the maximal class that belongs to that cluster.
# Test samples are labeled based on which cluster they belong to
################################################################################

def kmeans_classification():
    x_train, x_test, y_train, y_test = load_digits()

    # plot some train data
    N = 25
    l = int(np.ceil(np.sqrt(N)))

    im = np.zeros((10 * l, 10 * l))
    for m in range(l):
        for n in range(l):
            if (m * l + n < N):
                im[10 * m:10 * m + 8, 10 * n:10 * n +
                    8] = x_train[m * l + n].reshape([8, 8])
    plt.imsave('plots/digits.png', im, cmap='Greys')

    n_cluster = 30
    classifier = KMeansClassifier(n_cluster=n_cluster, max_iter=100, e=1e-6)

    classifier.fit(x_train, y_train)
    y_hat_test = classifier.predict(x_test)

    assert y_hat_test.shape == y_test.shape, \
        'y_hat_test and y_test should have same shape'

    print('Prediction accuracy of K-means classifier with {} cluster is {}'.
          format(n_cluster, np.mean(y_hat_test == y_test)))

    linear_classifier = LogisticRegression()
    linear_classifier.fit(x_train, y_train)
    y_hat_test = linear_classifier.predict(x_test)
    print('Accuracy of logistic regression classifier is {}'
          .format(np.mean(y_hat_test == y_test)))

    KNNClassifier = KNeighborsClassifier()
    KNNClassifier.fit(x_train, y_train)
    y_hat_test = KNNClassifier.predict(x_test)
    print('Accuracy of Nearest Neighbour classifier is {}'
          .format(np.mean(y_hat_test == y_test)))

    np.savez('results/k_means_classification.npz',
             y_hat_test=y_hat_test, y_test=y_test, centroids=classifier.centroids, centroid_labels=classifier.centroid_labels)


#if __name__ == '__main__':
#    kmeans_toy()
#    kmeans_image_compression()
#    kmeans_classification()
